### ISSUE TITLE
Behavior of Span.End is unclear.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#1010]
The behavior of Span.End could use some clarifications. For example, I think I heard from @tsloughter that in Erlang, ending a Span inactivates it on a Context there, which seems problematic, especially after Context is the only way to specify a parent span. Other points that are unclear are when a span needs to be ended, and what the relation to IsRecording is.

I created PR #1011 to clarify these points.

**Comment by tsloughter** [comment]
So, yes, we don't have users use `Span.End` directly in Erlang/Elixir, similar to why Java uses `Scope` instead of requiring a user to explicitly call `End` and then manually change the active span to the previous active Scope's span.

Instead users use `ot_tracer:end_span(Tracer)` which ends the active Span in the current context.

This allows for `Tracer` to be responsible for Span Processors, if it wasn't then we'd have to copy Span Processors from the `Tracer` into each started Span.

The Tracer's `end_span` calls the Span modules `end_span`, runs the `OnEnd` processors and then makes the Span that was previously active now active and the current active span no longer active.

So it isn't a function of Erlang's `Span.End` that inactivates the Span in the Context but a function "above" that, currently in the `ot_tracer` module.

**Comment by andrewhsu** [comment]
from the issue triage mtg today with TC, allowing changes related to this issue for GA if editorial changes only

**Comment by tsloughter** [comment]
I'd be interested in seeing how other languages allow users to end a span and return to the previously active span. I don't think I've seen any that requires the user do:

```
PreviousSpan = Tracer.get_active_span()
Span = Tracer.start_active_span()
Span.End()
Tracer.set_active_span(PreviousSpan)
```

**Comment by tsloughter** [comment]
I guess what I'm suggesting is adding an `End` in "Tracer Context Utilities" that ends the active span and updates the context. But maybe only Erlang "needs" this?
