### ISSUE TITLE
Sampler.ShouldSample parent parameter should be Context

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-specification#1024]
This is a tracking issue for PR #881: `Sampler.ShouldSample` should be changed to receive the full parent `Context` instead of the parent `SpanContext`, as there is no reason to only provide the SpanContext, and it is one of the few remaining places in the spec where we deal with a bare SpanContext.

**Comment by Oberon00** [comment]
Since spec is frozen, this probably has to be after-ga (even though I had originally tagged the PR required-for-ga), except if we say it is related enough to #1019.

**Comment by bogdandrutu** [comment]
The only problem with this is if we want to extend in the future to support delayed calls to Sampler because that requires holding a reference to the parent Context. But that itself is a new feature which requires more changes, so because we do not intend to support that I am fine with having this now
