### ISSUE TITLE
Remove getters for span status fields from the API

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-specification#1037]
**What are you trying to achieve?**
Remove the following methods from the [Span Status interface](https://github.com/open-telemetry/opentelemetry-specification/blob/dc5b511e5f664e8d98cd317ceceb593cfbbcc14e/specification/trace/api.md#status):
* [GetCanonicalCode](https://github.com/open-telemetry/opentelemetry-specification/blob/dc5b511e5f664e8d98cd317ceceb593cfbbcc14e/specification/trace/api.md#getcanonicalcode)
* [GetDescription](https://github.com/open-telemetry/opentelemetry-specification/blob/dc5b511e5f664e8d98cd317ceceb593cfbbcc14e/specification/trace/api.md#getdescription)

**Additional context.**
The spec is currently inconsistent as it defines the two getters mentioned above on the Span Status object, but no API on the Span itself to get the Status object to call these getters on. In order to make these getters available on the API, implementations either have to expose the enclosed Status via a getter on the span, or have the API designed in a way that allows users to keep a reference to the Status object they created for that span. Note that the spec does not require Status to be immutable.

From #1029, which had the same intent but assumed the getters above would be directly on the span, whereas they are actually on the Status object enclosed by a span:

We do not want any getters on spans, as it leads to inconsistent behavior which we do not want users to rely upon. Due to overhead concerns, we do not want the public API to force the underlying implementation to retain any state. Examples of implementations which do no include: 
* no tracer installed
* sampling enabled
* streaming implementations

Examples of cases where getters could bite users:
* Using status to control application behavior. For example, setting trace status to Error, then switching behavior based on checking the status. This will not always work as expected.

If users which to use this information in their application, they can store it as a separate item in the context object (or as baggage), rather than rely on the span itself.

cc @tedsuo

**Comment by Oberon00** [comment]
> We do not want any getters on spans, as it leads to inconsistent behavior which we do not want users to rely upon

Your argument is invalid 😉 There are no getters on the span for that. Please clean up the issue description, quite a few arguments in it do not apply to getters on status as opposed to span.

**Comment by andrewhsu** [comment]
from the issue triage mtg today, marking as required for ga to come to an agreement of whether we need this change or not. if so, needs to get implemented.

if consensus cannot be reached by next week, desire is to leave the spec the way it is.

assigning to @arminru to drive

**Comment by bogdandrutu** [comment]
## Proposal

I would go with a more aggressive approach, let's remove the requirement to have a "Status" object in the API (the object, not the concept) where possible, and how it is implemented is language specific. We should NOT forbid to have a `Status` object with getters (see the next section for way that is a valid pattern).

This is very language specific (and we need to understand that specs will apply to different languages), and I see few ways to implement this API (at least in the languages that I am familiar with, there may be other ways as well):
1. Use overloads where language supports that. We will have a `setStatus` API that allows recording `StatusCanonicalCode` and optional `Description` (a.k.a. an overload API).
2. Use variadic arguments where language supports that and it is canonical in that language. For example in golang I can see an API `SetStatus(code StatusCanonicalCode, opts ...StatusOptions)` where possible `StatusOptions` is `WithDescription`.
3. In languages where it is not idiomatic or not possible to support overloads or variadic arguments, an object called `Status` can be defined to avoid the api explosion (e.g.  may be hard to have `SetStatus` then `SetStatusWithDescription` then in the future we add property `Foo` will have `SetStatusWithDescriptionAndFoo` and `SetStatusWithFoo`). In this case the API MUST provide the getters for this object because implementation needs to retrieve the properties (but does not need to provide getters for the status from the Span).

Also the similar logic applies to `Link` and `Event`, where based on the language capabilities and idiomatic patterns one of the previous options can be used.

It may also benefit if we have a section that refers to some common possibilities (as exposed above) that can be reference from status/event/link apis, just for developers to understand better their possibilities.

## Previous comments

>> In order to make these getters available on the API, implementations either have to expose the enclosed Status via a getter on the span,

>Good point, the spec could be interpreted this way. In that case I would even vote for making this required-for-ga

This is a wrong implementation of the specs, the need for getters is for the implementation to be able to access the values, not for the user of the API to access the Status of the Span, hence the reason no getter for the Status from the Span.

**Comment by bogdandrutu** [comment]
I was thinking where I would do the version 3, and I think in C++ I would go with having these objected defined as `struct` to have a smaller api surface

**Comment by arminru** [comment]
@bogdandrutu I think all three options you mentioned are reasonable and the spec should allow for each of them, depending on what's idiomatic for the respective language.

> This is a wrong interpretation of the specs, the need for getters is for the implementation to be able to access the values, not for the user of the API to access the Status of the Span, hence the reason no getter for the Status from the Span.

I see. I could imagine that's a quite common misinterpretation so we should improve the wording here or add a note for the getter's purpose if we keep them in this form.

**Comment by bogdandrutu** [comment]
@arminru I agree especially that it is written only for Status that way and people may think that is special. Cleanup there is welcome.

**Comment by Oberon00** [comment]
I think we should still remove the getters but we can add a note that APIs MAY expose getters if it's required for implementations to access it.

**Comment by bogdandrutu** [comment]
Not a strong opinion, I would like to see the text, but want to make sure as I said that in all 3 cases event/link/status all 3 options I mentioned are possible and clear for the SDK devs as well as for the user (that this is not for instrumentation purpose)
