### ISSUE TITLE
should StatusCanonicalCode be applied for rpc?

### ISSUE THREAD

**Issue by eddynaka** [open-telemetry/opentelemetry-specification#1044]
**What are you trying to achieve?**

After the merge of this PR: https://github.com/open-telemetry/opentelemetry-specification/pull/966, we can see that the `StatusCanonicalCode` got changed to `Error`, `Unset`, and `Ok`.

But, if we see the rpc status: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/rpc.md#status, they kept the same.

**Additional context.**

Should the status be the same? How should we map the rpc status to the new `StatusCanonicalCode`? For example: `Unkown` is an error or an unset status?

cc: @cijothomas @reyang

**Comment by cijothomas** [comment]
@tedsuo

**Comment by arminru** [comment]
Good catch, this needs to be updated. Thanks @eddynaka!

**Comment by arminru** [comment]
In order to resolve this, we'll need to do two things:

1. Add a mapping from GRPC Status Codes to our new OTel Status Code (Unset, Ok, Error), e.g.
  - OK --> Ok
  - CANCELLED and UNKNOWN --> undefined (up to the user) or leaving Unset
  - all the others --> Error
2. Add a new attribute (e.g., `rpc.grpc.status_code`) to store the GRPC Status Code, which would otherwise be lost now that we have a different and considerably reduced set of Status Codes in OTel

**Comment by eddynaka** [comment]
Hi @arminru , thanks for mapping!

Do you have a timeline to be official in the spec?

**Comment by Oberon00** [comment]
@arminru I think the mapping will have to match the mapping we have defined in the proto, see https://github.com/open-telemetry/opentelemetry-proto/pull/224. And there AFAIK the current proposal is OK -> UNSET, everything else -> ERROR.

**Comment by andrewhsu** [comment]
@carlosalberto from the issue triage mtg today, assigning to you since you previously worked in this area

**Comment by eddynaka** [comment]
Just to get a clear response. 


For HttpStatusCode:

- `>= 100 && <= 399` -> UNSET
- ERROR (otherwise)

For RPC:
- `OK` -> UNSET
- ERROR (otherwise)

**Comment by Oberon00** [comment]
For HTTP, the mapping is already defined (indeed like you describe it) here: https://github.com/open-telemetry/opentelemetry-specification/blob/4b19e006ede63471103925edc6a15ab1d7579944/specification/trace/semantic_conventions/http.md#status

For RPC, I think that mapping makes sense, but we need to specify it in the semantic conventions. A PR would be welcome for that 😃

**Comment by eddynaka** [comment]
Hi @Oberon00 , in the .NET implementation, in the Status, we have a property that is called `IsOk`. Before this change, this property was easy, so if the canonical was `Ok`, so `IsOk` would be true.

But now, we have a different situation, since the instrumentation won't set to `Ok`, can we assume that `Ok` and `Unset` are `Ok`?

Not sure if that was clear enough...

Thanks.

**Comment by arminru** [comment]
@Oberon00 oh yes of course. I forgot that we don't have the status source from the status OTEP in the API (yet?), which would make an instrumentation-determined `Ok` distinguishable. In this case, your and @eddynaka's proposal makes sense.

**Comment by andrewhsu** [comment]
from the spec issue triage mtg today, after discussing this issue sounds like this can be changed to allowed-for-ga since it is not a blocker for trace spec freeze

**Comment by pcwiese** [comment]
I don't understand how this cannot be a blocker for GA. The change in the status code spec stomped all over the status code emitted from RPC spans. Without defining a specific tag to carry that status code the receivers of the traces (collector + exporters) won't have any idea how to report the actual RPC status to the backend. My team definitely relies on that breakdown of RPC failure codes.

I'm 100% in favor of passing this information along in an attribute with key "rpc.grpc.status_code". We need something here otherwise the collectors are going to start dropping a key piece of information when they start consuming the new OTLP proto files.

**Comment by Oberon00** [comment]
It is not a blocker for release since (1) OpenTelemetry as a whole is usable even without it and (2) it can be added after release as a non-breaking change, if it does not make it into the release.

**Comment by toumorokoshi** [comment]
We just hit this too: https://github.com/open-telemetry/opentelemetry-python/pull/1308. So filed a PR with the results of the discussion.
