### ISSUE TITLE
Why are we using such a long name as StatusCanonicalCode?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-specification#1069]
From https://github.com/open-telemetry/opentelemetry-specification/pull/1067#discussion_r500495896.

Another question is: Are there non-canonical status codes?

**Comment by Oberon00** [comment]
I think this should be renamed to just Status (or StatusCategory) after #966. The current enum is not canonical and I also don't know if we want to call it a code.

**Comment by arminru** [comment]
I don't think this is a blocker for GA but if we intend to change that (and from the 👍 on here we seem to have some consensus), we should do so before GA. It should be a simple find-and-replace for SIGs that have already adopted the new Status model and otherwise it would go well along with that change.

**Comment by tigrannajaryan** [comment]
I'd prefer to settle this before GA since the names may be part of the API. In that case changing the names will break the API.
