### ISSUE TITLE
Clarify purpose of `PropagatedSpan`

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-specification#1087]
From the discussion on #1086 and as discussed in the SIG spec meeting:
We should clarify the purpose of `PropagatedSpan` since the current description in the API seems to be confusing.

**Comment by anuraaga** [comment]
My recommendation would be to rename it to what it is, rather than how it's used, which is more conventional for type names I think. `NonRecordingnSpan` or `NoopSpan` perhaps. A couple of issues with the current name

- The span may not be locally propagated - a user may just read a spancontext and drop the span, for example when adding links.
- The span may not be remote propagated if it's invalid
- Having a propagated span seems to indicate there is also a such thing as a non-propagated span, but all spans can be propagated. It would be quite unfortunate to see users wrap a real span expecting its a requirement for propagation, e.g. `Span.getPropagated(spanBuilder.start().getContext()`. This code doesn't seem that bad at a glance.

**Comment by Oberon00** [comment]
> for example when adding links

That counts as propagation IMHO.

But I agree that PropagatedSpan (especially the past tense form) is not a good name.

**Comment by carlosalberto** [comment]
`NonRecordingSpan` is fine, but I don't like `NoopSpan` as we are not *entirely* no-op.  Now I started wondering if we should also consider the original `BlankSpan` ;)

@bogdandrutu IIRC you were interested in driving this?

**Comment by Oberon00** [comment]
>  I don't like NoopSpan as we are not entirely no-op.

I think we are entirely no-op if you don't consider getters as "operations".

> Now I started wondering if we should also consider the original BlankSpan ;)

We are definitely not blank, the only Getter (except IsRecording) that is accessible can return a non-blank SpanContext.

**Comment by jmacd** [comment]
I'd like to clarify whether an SDK can use `PropagatedSpan` (or `NonRecordingSpan`, a name I prefer) to capture span duration measurements and span attributes, even though these spans are non-recording. The key question is: when a trace sampling decision decides not to record a span, may we use a `PropagatedSpan` in its place? If so, could a Metrics SDK capture these non-recording non-remote span durations and record them as metric events?

**Comment by Oberon00** [comment]
> I'd like to clarify whether an SDK can use PropagatedSpan (or NonRecordingSpan, a name I prefer) to capture span duration measurements and span attributes, even though these spans are non-recording. 

No, it can't. Creation of them is fully implemented in the SDK and should not be overridable. Also, not being able to do so is the whole purpose of them, isn't it?

**Comment by jmacd** [comment]
> not being able to do so is the whole purpose of them, isn't it?

Well I guess the goal of this issue is to clarify their purpose. Is the purpose strictly for this case of injecting span identifiers from a remote process? If so maybe a better name would be `PropagatedRemoteSpan`.

This means PropagatedSpan is not meant to be used for propagating context within the process via a non-recording span, i.e., a "no-op span with real identifiers" that could be used for negative sampling decisions or span-to-metric applications.

**Comment by Oberon00** [comment]
> This means PropagatedSpan is not meant to be used for propagating context within the process via a non-recording span, i.e., a "no-op span with real identifiers" that could be used for negative sampling decisions or span-to-metric applications.

Why can't it be used for that?

**Comment by jmacd** [comment]
We discussed this in spec SIG, there is some interest in removing this concept from the public-facing API, which means making it an anonymous class. There is also interest in removing this concept and going back to the "two context keys" model for Extract().

AI: @tsloughter will write up a new issue. Thank you.

**Comment by Oberon00** [comment]
> removing this concept from the public-facing API, which means making it an anonymous class. 

The current spec allow this. In fact, Java has implemented it that way.
