### ISSUE TITLE
Add BeforeEnd to have a callback where the span is still writeable

### ISSUE THREAD

**Issue by gugahoa** [open-telemetry/opentelemetry-specification#1089]
**What are you trying to achieve?**
Set an attribute to all spans in a trace

**What did you expect to see?**
Writeable spans on SpanProcessor's OnEnd(Span)

**Additional context.**
What I tried to implement is a feature called trace field in Honeycomb (reference: [`AddFieldToTrace`](https://godoc.org/github.com/honeycombio/beeline-go#AddFieldToTrace))

For that I first tried to use [`SpanProcessor`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#span-processor), but soon  found out that [`OnEnd(Span)`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#onendspan) is not writeable.

The solution I arrived was to write a custom exporter which was able to read from a thread-local storage (at the time of the implementation, Baggage had yet to be spec'ed out) to list all attributes related to a Trace and insert into the span before exporting.

From what I understood from the [`SpanProcessor`](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#span-processor) specification, that's the place where I should have placed this logic, as it's a transformation that should happen before the span is sent to any exporter

**Comment by garthk** [comment]
Required for dynamic resource-like attributes desired in every span but computed at run-time because they're not constant, _eg._ instance uptime and recent CPU utilisation. Injecting them in the exporter gives results that become less accurate during the spikes we're most interested in.

**Comment by arminru** [comment]
IIRC it was discussed to make spans writeable in OnEnd but this was left out because users will not always have full control over the order in which span processors are registered and in turn invoked, which could result in unreliable behavior.
From your use case it sounds like you would not need any attributes that are added/overwritten in OnEnd visible to any other span processor, right? If you only need to have those changes reflected once passed to exporters, this shouldn't be an issue then.

@carlosalberto you seemed to remember some of that discussion as well in the meeting yesterday. Do you know the rationale for that decision?

**Comment by iNikem** [comment]
Why these attributes cannot be set in `onStart`, which already has writable span?

**Comment by arminru** [comment]
Reading the spec again, I noticed that it explicitly says that spans are already marked as ended at the time they are passed to SpanProcessor.OnEnd:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#onendspan

> `OnEnd` is called after a span is ended (i.e., the end timestamp is already set). 

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#end

> End: Implementations SHOULD ignore all subsequent calls to `End` and any other Span methods, i.e. the Span becomes non-recording by being ended (there might be exceptions when Tracer is streaming events and has no mutable state associated with the `Span`).

We would also have to change either of those requirements if we wanted to make spans writeable in OnEnd and we would need to understand the consequences well.

**Comment by Oberon00** [comment]
Exactly. The difficult to get right (but specified!) order (exporting may happen before the other OnEnd processor) is another problem, but the main problem is that spans are already ended, as @arminru said. This was already discussed in https://github.com/open-telemetry/opentelemetry-specification/pull/669#issuecomment-654841632.

There are two ways we could go forward here:
* Use existing mechanisms in your implementation to modify the "SpanData", i.e. the readable representation of the span that the exporter gets, instead of the Span itself.
* We may introduce a new SpanProcessor hook BeforeEnd.

We definitely can't pass a writable span to OnEnd.

**Comment by tsloughter** [comment]
Why not define it as your Span Processor must assume it gets the Span in the form it is ended with and not expect to have any changes from previous processors visible?

**Comment by tsloughter** [comment]
@iNikem my understanding is that it is because `OnStart` can't be used to implement the Honeycomb feature https://godoc.org/github.com/honeycombio/beeline-go#AddFieldToTrace -- it would only be able to add the attribute to spans started after this call, but it is supposed to be able to add them to all local spans in the trace, even if already started.

I'd be fine with a `BeforeEnd` span processor, but don't really like adding more hooks when as far as I can tell the only issue is to define that `OnEnd` processors can't depend on each other and that if you have multiple processors writing the same attribute you can't know which will actually be added last -- so a warning to use unique attribute keys.

**Comment by Oberon00** [comment]
No, the main issue is that in OnEnd the span is already ended, and for an ended span, SetAttribute should be a no-op. Changing that seems liable to opening a can of worms.

**Comment by tsloughter** [comment]
Ah, ok. Yea, I wouldn't want to change the fact that ended means read-only but instead move the "ending" to after the processors. But this isn't possible since one of the processors is what takes the "ended" span and passes it to the exporter... I didn't like exporting being part of processors because of this.

And probably too late to argue that sending to the exporter should be separate and unrelated to processors, leaving OnEnd processors to act like "BeforeEnd" :(

**Comment by Oberon00** [comment]
Maybe we would even need a special state where the span is semi-ended, i.e. it has IsEnded==true and has an end timestamp, but is still recording.

**Comment by iNikem** [comment]
> @iNikem my understanding is that it is because `OnStart` can't be used to implement the Honeycomb feature https://godoc.org/github.com/honeycombio/beeline-go#AddFieldToTrace -- it would only be able to add the attribute to spans started after this call, but it is supposed to be able to add them to all local spans in the trace, even if already started.

I don't understand. If you have a `SpanProcessor` registered, it will receive all spans created in the given process. And so it will be able to add attributes to all spans. You don't "do a call" manually. All spans are handed to you.

**Comment by tsloughter** [comment]
@iNikem it only receives a write-able span for `OnStart`, meaning if spans are already started in the trace you will not be handed those spans at a point that you have the attributes and can write to the span.

**Comment by iNikem** [comment]
It seems I still don't understand your use-case: what are these attributes that are not available right away but become available only when some spans were already started?

And even more: how does `onEnd` differ from `onStart` in this regard? I fail to see how you hoped to achieve your goal with `onEnd` that you cannot do in `onStart`?

**Comment by tsloughter** [comment]
> It seems I still don't understand your use-case: what are these attributes that are not available right away but become available only when some spans were already started?

An HTTP user id parsed out of headers is the best example I can think of, but actual honeycomb users (@garthk @gugahoa ?) probably have more. The initial request span is started right away, before user code parses out headers they care about, a child span is started when the user's logic is called at which point they parse out the user-id and want to put it on all spans in that trace but the span created when the HTTP handler got the request has already run `OnStart` so the only time it could be added is `OnEnd` -- without manually going through the stack and adding the attribute.

**Comment by seh** [comment]
That's a good characterization, @tsloughter. This has been a "normal" way of using Honeycomb's Beeline library for a long time. It buffers the trace span tree in memory, and can distribute attributes (called "fields" there) up and down the span tree before sending the spans to the server. It [stores a set of fields on the trace itself](https://github.com/honeycombio/beeline-go/blob/main/beeline.go#L243), in [a field on the `trace.Trace` type called "traceLevelFields."](https://github.com/honeycombio/beeline-go/blob/2e2795d005c84da36d687aa3d6422e64982a86d5/trace/trace.go#L45) You can see the transcription from that field down to each span just before sending each [here](https://github.com/honeycombio/beeline-go/blob/2e2795d005c84da36d687aa3d6422e64982a86d5/trace/trace.go#L446-L451).

**Comment by bogdandrutu** [comment]
I am curios why do you need to still add events/attributes to the `Span` when you can do that directly on the `SpanData` that we will export? What is the advantage to change the `Span` vs modifying the data that will be exported directly?

**Comment by Oberon00** [comment]
Agree with @bogdandrutu. I'm not sure which implemenation language you are using but in Java there is https://github.com/open-telemetry/opentelemetry-java/blob/v0.9.1/sdk_extensions/tracing_incubator/src/main/java/io/opentelemetry/sdk/extensions/incubator/trace/data/SpanDataBuilder.java

Unfortunately, #158 is not resolved so this is all a bit vague in the spec.

**Comment by Oberon00** [comment]
> Where is there a pluggable place to modify SpanData before export?

The exporter interface. You can make your own exporter that wraps an existing one and does the modification.

**Comment by Oberon00** [comment]
@iNikem 
> Processor can certainly modify SpanData

True, but in order for the "modification" (SpanData is immutable at least in Java, so it actually creates an updated copy) to be picked up by an exporter, that exporter must be invoked in the same OnEnd.

**Comment by gugahoa** [comment]
@bogdandrutu 
> I am curios why do you need to still add events/attributes to the Span when you can do that directly on the SpanData that we will export? What is the advantage to change the Span vs modifying the data that will be exported directly?

That would mean writing my own processor which will export to the configured exporters, but I wouldn't want to write my own processor for that and instead it would be preferable to rely on tried-and-true processors such as the BatchProcessor

@Oberon00 
>The exporter interface. You can make your own exporter that wraps an existing one and does the modification.

I'm not sure this translates well to Erlang, but I need to try it out first to see how it goes

**Comment by tsloughter** [comment]
> The exporter interface. You can make your own exporter that wraps an existing one and does the modification.

That is what we hoped not to have to do and I believe is already the way people have been doing it.

But I guess if its a wrapper that can take any exporter it and be a new exporter that acts on the attributes and then calls the wrapped exporter with the modified batch it wouldn't be too bad.

It would certainly be more efficient to update "on end", but it sounds like a wrapper exporter is the way to go -- assuming there aren't issues with the lifetime of the shared attributes on a trace, will have to talk to those using it.

**Comment by tsloughter** [comment]
> I'm not sure this translates well to Erlang, but I need to try it out first to see how it goes

It does. We have an exporter behaviour, `otel_exporter`. You can create a new exporter that simply goes through all the spans and instead of exporting them it updates their attributes in the table and then calls the `export/2` function of the wrapped exporter.

And has to call the `init/1` of the wrapped exporter when its `init/1` is called at startup.

**Comment by iNikem** [comment]
> It would certainly be more efficient to update "on end"

You seems to have an implicit assumption that for each span all its parent spans from the same trace will _end_ after it. That assumption is wrong. Parent span can end even before child span starts.

**Comment by seh** [comment]
> Parent span can end even before child span starts.

What does that represent? Perhaps an asynchronous task spawned by the parent that took a while to start?

**Comment by tsloughter** [comment]
> > It would certainly be more efficient to update "on end"
> 
> You seems to have an implicit assumption that for each span all its parent spans from the same trace will _end_ after it. That assumption is wrong. Parent span can end even before child span starts.

I know, this feature can't be perfect, there will be missed spans in some specific cases, but for many cases it appears to be useful and work just fine.

**Comment by iNikem** [comment]
> > Parent span can end even before child span starts.
> 
> What does that represent? Perhaps an asynchronous task spawned by the parent that took a while to start?

Async servlet/Spring webflux controller. Controller method will return and its span will finish before async result starts actual computing.

**Comment by garthk** [comment]
If we're not up for changing the behaviour of `OnEnd` to `BeforeEnd`, but some users need something with `BeforeEnd` semantics, why not add a `BeforeEnd`? 

The alternative seems to be to either lose our time correlation or build amusing workarounds like using `OnEnd` to create a child span with the data we couldn't add to this one, and wrapping the exporter we want in another one which first buffers spans for long enough to reliably find the disposable spans, copy attributes from them to their parent, and then discard them, and then calls the original exporter. It's possible, but it's a lot of work to force on our users.

**Comment by Oberon00** [comment]
@garthk You make it sound very complicated. What is that about buffering something long enough? I think I don't understand your use case after all. I thought you simply wanted to do something like

```java
  @Override void OnEnd(ReadWriteSpan span) { span.setAttribute("foo", "bar"); }
```

which translates to

```java
  @Override CompleteableResult export(Collection<SpanData> spans) {
    Collection<SpanData> modified = new ArrayList<SpanData>(spans.size());
    for (SpanData span: spans) {
      Attributes newAttributes = Attributes.newBuilder(span.getAttributes()).setAttribute("foo", "bar").build();
      modified.add(SpanDataBuilder.newBuilder(span).setAttributes(newAttributes).build());
    }
    return wrappedExporter.export(modified);
  }
```

Sure, this is more allocation-heavy and a bit awkward, but it is functionally equivalent at least.

**Comment by garthk** [comment]
The reporter works on the span later than the end of the span, and runs in a different process. It can't collect data at the relevant time or from the relevant process without help. `OnEnd` can, but it's got nowhere to put the data without extra machinery. You're correct: the extra machinery would be complicated. I'd prefer not to build it, nor insist our users build it to meet that need. I'd prefer the spec granted that implementations MAY provide a means for the configured tracer to call code to modify the span prior to it reaching a state we consider final.

**Comment by Oberon00** [comment]
>  It can't collect data at the relevant time or from the relevant process

Right, but if you want to collect process data, you can use OnStart. If you need to do something based on span attributes, use the exporter wrapper. If you need to do both, you can transform the relevant process data into attributes in OnStart and remove them in the exporter wrapper.

**Comment by garthk** [comment]
I'm sorry, I should have given concrete examples. Here's one with time _and_ process locality: a span attribute for the number of reductions performed by the process during the span.

Reductions are an excellent proxy for CPU effort, and cheap to measure. I'd much appreciate having a reductions count on all my spans, including those generated by my dependencies and their integration dependencies. 

Third party code rules using a function or macro to wrap the code and gather the information at the appropriate time.

I could use `OnEnd` to take the last measurement, but due to the read-only span it couldn't put that measurement or its delta into the span's attributes.

If the process weren't dead by the time the reporter got the span, it'd likely have done some more work, forcing the use of some other mechanism.

All this might be peculiar to our ecosystem, so I'd suggest an RFC 2119 MAY instead of a MUST for providing a `BeforeEnd` or other suitable way to configure our tracer to meet this requirement.

**Comment by carlosalberto** [comment]
I'd be fine adding this additional `BeforeEnd`, although not sure about the timeline (in theory we could still add it, specially if it has a MAY for now, given it's on the SDK level). @bogdandrutu opinion on this?

**Comment by ahayworth** [comment]
👋 We'd appreciate an optional `BeforeEnd` hook as well - internally at GitHub we have some complex filtering requirements for any data that may leave our datacenters (such as trace data, which currently goes to a SaaS). We're currently not able to run the opentelemetry collectors for filtering, and that leaves us attempting to scrub spans of sensitive data before they're emitted. [1]

Wrapping SpanProcessors or writing custom SpanExporters is certainly feasible, and we're implementing that solution now. However, a `BeforeEnd` hook would allow us to implement our (arguably esoteric) filtering needs in a much more ergonomic and sustainable way.

If nothing else, consider this an alternate use-case for a `BeforeEnd` hook other than annotation of spans with additional data - we need to possibly _remove_ unintentional attributes and events.

---

[1] Of course, I wish we didn't need to do last-minute, best-effort scrubbing. I wish sensitive data didn't leak out of exceptions and events in the first place. Not emitting sensitive data is the best practice! But we can't always ensure that, and the consequences of mistakes can be severe, so we always attempt a last-minute scrub for known types of sensitive data, just in case.

**Comment by pyohannes** [comment]
We'd appreciate a `BeforeEnd` hook as well. Our use case: we want to change the span status for 404 HTTP errors. We can't use the collector.

Writing custom `SpanExporter`s is suboptimal: it involves additional allocations (a span needs to be copied), and it involves additional implementation effort (we'd need to wrap every exporter we use, instead of just having one processor that can be used with any exporter).

**Comment by anuraaga** [comment]
> it involves additional allocations (a span needs to be copied), and it involves additional implementation effort (we'd need to wrap every exporter we use, instead of just having one processor that can be used with any exporter).

I generally agree with the usefulness of `BeforeEnd`, just want to confirm these points. At least in Java, we have these mechanisms

- [DelegatingSpanData](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/tracing-incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/trace/data/DelegatingSpanData.java) so it's mostly only attributes that are copied, not span. And if the attribute copy isn't ideal, we could also add `DelegatingAttributes` (hooray for Attributes being an interface!)

- [SpanExporter.composite](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SpanExporter.java#L45). For the implementation effort, is it not something like `AttributeModifyingExporter.create(SpanExporter.composite(exporter1, exporter2))`?

Just want to check on how useful these current mechanisms are for your use case. Thanks.

**Comment by pyohannes** [comment]
> Just want to check on how useful these current mechanisms are for your use case. Thanks.

Those mechanisms could be useful, if they were spec'd out and available for all languages. However, it seems to me `BeforeEnd` is a simpler and cleaner solution.

**Comment by Cavvar** [comment]
Hello everyone!
I just wanted to add that a solution with something like a `beforeEnd` hook would still be appreciated!

**Comment by DenisAngeletta** [comment]
> Hello everyone! I just wanted to add that a solution with something like a `beforeEnd` hook would still be appreciated!

Any chance this gets any traction?

**Comment by tsloughter** [comment]
Curious if any implementation has a solution to, or anyone has an argument why it isn't needed, for adding baggage to attributes of the currently active span?

I could see an argument that it would be rare to be needed and that in most cases you could instead set the baggage and then do a delayed start of the span by setting the timestamp on start, but that feels like unnecessary and confusing hoops for the end user to deal with simply because we don't allow the baggage attribute to be added at the end.

**Comment by Oberon00** [comment]
> you could instead set the baggage and then do a delayed start of the span by setting the timestamp on start

Not sure why you would need to add a timestamp in that case? I guess it could be slightly more correct, but setting the baggage before starting the span is no different from providing attributes at startup, or even "calculating" a span name. You could say, not using an explicit timestamp is almost always slightly incorrect (and the API is sorely lacking a method to get an appropriate timestamp).

On the other hand, adding baggage OnStart vs. On(Before)End may happen in potentially completely different contexts. Lately, I've been thinking that decoupling spans/tracers from Context in the way we did might have been *too* flexible.

**Comment by tsloughter** [comment]
If there isn't a need to set the timestamp for the start time then there wasn't really a conflict between adding baggage onstart and onend in the first place.

But if your start and end time would be the same because you have to "start" the span at the end then you need to pass in the actual start time of the operation.

And this is even assuming the user starts the span and not something they've included like a middleware or automatic instrumentation.

**Comment by DenisAngeletta** [comment]
The reason why a `beforeEnd` hook is so valuable is because a way to set attributes in a span when it ends can be beneficial for use cases like @garthk described [here](https://github.com/open-telemetry/opentelemetry-specification/issues/1089#issuecomment-708015650).

A current workaround could be to write a custom `SpanProcessor` that takes a `SpanExporter` and essentially mimicks the behaviour of a `SimpleSpanProcessor`. The only problem in this case is, that we send spans to n+1 exporters, with `n` being the amount of exporters you actually define through `OTEL_TRACES_EXPORTER`. Sending multiple times could be avoided by utilizing the [AutoConfigurationCustomizerProvider](https://github.com/open-telemetry/opentelemetry-java/blob/1e073fcff20697fd5f2eb39bd6246d06a1231089/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizerProvider.java#L9).

**Comment by Oberon00** [comment]
@tsloughter Ah, I think I just misunderstood you. I thought it would be OK to have the baggage around the start time, instead of around the end time. If the use case semantically needs the end time, then that won't help of course. Main problem is that you can't create child spans, even if you delay the start.

I do think BeforeEnd is a useful callback, in general.

**Comment by tsloughter** [comment]
An interesting solution I learned about yesterday is to have sort of sub-processors. The spec already mentions decorators on built-in span processors and so having a processor wrap a processor could be considered to fit that description.

Essentially it means the addition of baggage is done by creating a new Span with the attributes in a "processor" that wraps another (like the simple or batch processor) and passes the new Span to it.

I'm not sure if that makes sense how I've written it but I think it is likely a better solution than `BeforeEnd`. I can try to explain better in the spec SIG meeting today.

**Comment by Oberon00** [comment]
This would then require knowing which processor you want to modify the results for and only apply to that on, right? So I think it's a slightly different use case, and more similar to doing it in the exporter (https://github.com/open-telemetry/opentelemetry-specification/issues/1089#issuecomment-708991092).

**Comment by tsloughter** [comment]
You'd only need to know the processor in the sense you have to wrap something. Tho the SDK could do it for the user I would think, if the user sends an option to say wrap processors in X or something.

**Comment by Oberon00** [comment]
If you are interested in adding attributes to multiple spans, please take a look at this related OTEP: https://github.com/open-telemetry/oteps/pull/207 "Propose Context-scoped attributes"

**Comment by garthk** [comment]
Thanks; left them a comment. Meanwhile I'm having trouble following how the wrapped processors would work but I'm paid to think in other languages these days, which might not be helping. :)

**Comment by vetinari** [comment]
We need this also. Is there anything we can do to get progress on the `BeforeEnd()`?

**Comment by tsloughter** [comment]
Discussion has led to the desire for a more general change to processors for pipelines of "something" (I don't know what to call them since "processor" is already taken) within in each processor. This would allow for the modifications on spans that BeforeEnd.

But no progress aside from that being discussed in Spec SIG meetings has happened.

It has been in my backlog to work on for a long time but one stumbling block is simply naming :). In the collector there are pipelines with processors that feed each other, but since Span Processors already exist in the SDK that terminology can't be re-used. And no matter what is chosen it'll be confusing when compared against the collector.

**Comment by Oberon00** [comment]
TelemetryHandler? If the new "something" is meant to replace the processor, it might be the least confusing to name it "Processor2". Yes it's ugly, but also very clear.

**Comment by jackshirazi** [comment]
This issue was discussed at the March 28, 2024 Java SIG in the context of [adding stack traces to spans](https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/10973). This particular feature needs the equivalent of beforeEnd (taking a stack trace is expensive, so should only be done for long duration spans which you only know when the span is ended). The discussion suggested this was a compelling use-case for beforeEnd. Following @jack-berg suggestion, we (Elastic) will provide a Java implementation proof-of-concept for this use case, which hopefully will lead to a review of the benefit

**Comment by jack-berg** [comment]
I support this. Let's discuss at the 4/9/2024 Spec SIG meeting.

We're trying out a new spec issue management (described in #3821) flow where issues like this need a sponsor. I would be happy to sponsor @jackshirazi / @JonasKunz if one of you wants to take this on (i.e. own the spec PR, prototype).

**Comment by jack-berg** [comment]
Reading through the comments, the arguments **not** to do this seem to be:
- Its already possible to do this in a span exporter
- Doing this in a span processor requires paying attention to span processor ordering

But asking users to do this in span exporter is inconvenient and unintuitive - this is clearly a "processing" type of task so why would a user expect to have to do it in an exporter?

And yes, by doing this in a processor you have to pay attention to processor registration order, but that's expected and matches common sense expectations for processors. Notice that nobody expects to ignore processor ordering configuration in the collector. File configuration makes the registration order of processors [easy to configure](https://github.com/open-telemetry/opentelemetry-configuration/blob/6215d43ee00c4ebe32ca8cbaf4c2807600b73945/examples/kitchen-sink.yaml#L242).

This is the type of thing that is easy to do and fills an obvious conceptual flaw in the SDK design, where we've defined processors which can only process in a very constrained manner. Let's just fix it with the obvious / simple solution, which is to add a new optional beforeEnd method to SpanProcessor.

**Comment by tsloughter** [comment]
@jack-berg the end result I think was the replace the `decorators` feature` that was never defined.

**Comment by jack-berg** [comment]
Why introduce a new concept / SDK extension point instead of enhancing an existing? Limiting SDK extension points reduces cognitive load for users.

**Comment by tsloughter** [comment]
@jack-berg to make it possible to do similar to what this wants to do in OnStart as well.

**Comment by pellared** [comment]
Loose naming idea:
In .NET there is a pattern to name things callbacks like OnEnd (just after) and OnEnding (just before). We could name it `OnEnding` (instead of `BeforeEnd`).

**Comment by jack-berg** [comment]
Discussed in the 4/9/2024 Spec SIG meeting. There was agreement that we should look into solutions to accommodate a variety of use cases that require modifying spans near the end, including:
- Capturing expensive stack traces only if some condition is true
- Removing unwanted attributes that were added by instrumentation
- Schema transformation

Two broad families of solutions were suggested:
- Modify the span processor, e.g.
  - Add new beforeEnd operation where the span is still mutable
  - Evolve the onEnd operation to allow span to be mutated
- Codify the notion of a decorator, where the SDK provides tooling or an additional extension point to allow span processors to decorate / modify the ReadableSpan given the SpanProcessor#onEnd

@jackshirazi / @JonasKunz are either (or anyone else) interested / able to own this?

**Comment by JonasKunz** [comment]
I'm happy to own this.

**Comment by jack-berg** [comment]
Hi @JonasKunz - you've been assigned to the issue. Please reach out to me if needed. Thanks!

**Comment by JonasKunz** [comment]
I'd like to share my thoughts on the proposed families of solutions.

> * Modify the span processor, e.g.
>    * Add new beforeEnd operation where the span is still mutable
>    * Evolve the onEnd operation to allow span to be mutated

I think evolving the existing `onEnd` callback isn't the best solution here, because it technically is a breaking change:
Currently, span processors can assume that the span they are operating on in `onEnd` does not change during this call.
If the span becomes mutable, this is not the case anymore.

For the `beforeEnd` (or as suggested `onEnding`) callback this shouldn't be a problem in terms of backwards compatibility.
However implementors of `beforeEnd` would need to be aware of the fact that the span they are operating on might be changing from another thread, because in contrast to `onStart` the span has already escaped into the wild.

[Here](https://github.com/open-telemetry/opentelemetry-java/pull/6367) is a draft implementation showing how this new callback could be implemented in Java.

> Codify the notion of a decorator, where the SDK provides tooling or an additional extension point to allow span processors to decorate / modify the ReadableSpan given the SpanProcessor#onEnd

IIRC the main concern here from @jack-berg was that this introduction of a new component type might introduce too much complexity for SDK users and I share that concern.

However, having a pipeline-like structure where one stage can pass a wrapped, immutable span to the next stage is a lot more flexible than just the `beforeEnd` callback:
 * It allows to filter spans
     * Example use-case: We only want to export database spans which have a latency above a given threshold
     * Can be implemented by not invoking the next pipeline stage
     * Currently can be achieved by wrapping exporters, but this invalidates the batching performed previously in the `BatchingSpanProcessor`
 * Buffer spans and export them after some delayed notification:
     * First example use-case: Adding cloud provider resource attributes (e.g. [AWS](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/aws-resources). These resource attributes require costly operations (e.g. network calls) to be discovered. This currently requires a tradeoff: Either not add those attributes or delay the application startup until the costly operation has finished. The capability to buffer spans would open up a third option: Buffer the spans in a span processor, apply the new resource attributes when they are discovered and only after that pass the spans to the next stage
     * Second example use-case: Correlating spans with external profiling data. In [our distro](https://github.com/elastic/elastic-otel-java/blob/main/universal-profiling-integration/src/main/java/co/elastic/otel/UniversalProfilingProcessor.java) we add the ids of stack-traces recorded by the eBPF profiler to spans. This data arrives with a slight delay, so the spans need to be delayed and not immediately sent too.
     
I think we can get this flexibility without introducing an entirely new component and therefore with a lot less complexity.
[Here](https://github.com/open-telemetry/opentelemetry-java/pull/6394) is a backwards-compatible implementation showing how this could be done at least in Java.

The idea is to add a new parameter to `onEnd`: This parameter is a function which needs to be called with a span as argument. This function will invoke the next span processor in the "pipeline". This is a well known pattern, e.g. from [Java Servlet Filters](https://docs.oracle.com/javaee%2F6%2Fapi%2F%2F/javax/servlet/Filter.html#doFilter(javax.servlet.ServletRequest,%20javax.servlet.ServletResponse,%20javax.servlet.FilterChain)).

At least in Java, this functionality is very easy and cleanly addable in a backwards compatible way as shown by my implementation. However, I don't know if this is also the case for the other languages.

An alternative way to achieve the same capability would be to add a new `boolean initOnEndChaining(Function nextStage)` function to `SpanProcessor`. This function would be invoked by the SDK at initialization time in order to detect whether the `SpanProcessor` operates in chaining mode (it will call the next processor in line itself) or not (the SDK will be responsible for invoking the span processor after this processor).

This alternative solution is not quiet as elegant as my provided Java solution with the `onEnd`, but I think it should work in all languages.

It would be great to get your feedback here! As you might have noticed, I would prefer the decoration/chaining approach over `beforeEnd`, but by enhancing `SpanProcessor`s to do it instead of a new component.

**Comment by jack-berg** [comment]
> I think evolving the existing onEnd callback isn't the best solution here, because it technically is a breaking change:
Currently, span processors can assume that the span they are operating on in onEnd does not change during this call.
If the span becomes mutable, this is not the case anymore.

I agree but, but would also add that whether or not the `onEnd` method can be evolved to accept a new mutable span type as an argument will vary based what is allowed in a language and how it is implemented. I think in practice several languages will have to do something quirky to accommodate a change like this, like introduce a new onEnd method with a slightly different name, or a new SpanProcessor interface with a different name, or wait for a major version bump of the SDK. 

> However, having a pipeline-like structure where one stage can pass a wrapped, immutable span to the next stage is a lot more flexible than just the beforeEnd callback:

The idea that a processor isn't able to generically mutate _AND_ filter data makes it feel misnamed. With that said, the concept of a sampler at least partially overlaps with the filter use case. I wonder if its better to keep things separate, and instead of introducing a filter-chain concept in SpanProcessor, extend Sampler so there is a way to filter spans out on span end. Obviously any filtering that is done after the start of a span introduces the potential for broken spans, since downstream spans make sampling decisions based on the sampling status of their parent, which no longer reflects whether the parent span actually made it to the backend. Still, this use case comes up enough that its worth considering supporting and warning users to make sure they know the consequences.

Can anyone involved in the original trace SDK recall / comment on the reasoning why SpanProcessor wasn't initially designed with chaining in mind? The fact that it wasn't and therefore prevents the SpanProcessor filter use case seems deliberate rather than an oversight.
