### ISSUE TITLE
OpenTelemetry should use an allowed port

### ISSUE THREAD

**Issue by bboreham** [open-telemetry/opentelemetry-specification#1148]
**What are you trying to achieve?**

Conformance with Internet standards.

**What did you expect to see?**

A port number in the range of User Ports, and ideally one assigned by IANA.

**Additional context.**

OpenTelemetry is [using port 55680](https://github.com/open-telemetry/opentelemetry-specification/blob/cb25fe94d8d9378c04ee37d7802e7552cf5b6cc0/specification/protocol/exporter.md#configuration-options). According to [RFC 6335](https://tools.ietf.org/html/rfc6335#section-8.1.2), 
> a port number in [the Dynamic Ports range (49152-65535)] MUST NOT be used as a service identifier.

On a practical front, ports in the high range are usually allocated dynamically by the operating system, so there is some random chance 55680 is in use for that purpose and your OpenTelemetry receiver will not start.

**Comment by andrewhsu** [comment]
from the spec issue triage mtg today, setting to P1 so we can have a quick decision. perhaps setting the port number a required parameter will allow us to set it to a default we want to choose later.

**Comment by mtwo** [comment]
Following up from the same meeting. I'm making an IANA application now. I'll include the governance committee and @tigrannajaryan in all communications with them.

**Comment by mtwo** [comment]
@tigrannajaryan @bogdandrutu three questions that I need answered before I file this:

- Do we have a [list of defined TXT keys](https://tools.ietf.org/html/rfc6763#section-6.1)? I've entered our service name as 'otlp'
- "Please describe how your protocol supports security" - what should I enter for this
- I'm assuming that we only use TCP and don't use UDP - is this accurate?

**Comment by tigrannajaryan** [comment]
Does this proposal mean we need to change the default port? It will break a bunch of software that relies on the defaults.

**Comment by mtwo** [comment]
It does. Do you think the benefits of having a reserved port outweigh the pre-GA change? Bogdan also proposed an alternative of making the port a required parameter during RC and then defaulting it (via an optional parameter) to the newly-assigned port at GA.

If you think that it's too late and we should stick with our current port, then we can close this and I won't submit the request to the IANA.

**Comment by bboreham** [comment]
Server-side you can have the code listen to both old and new ports. The only hard break is for new-built clients that cannot be configured to talk to old servers.

**Comment by mtwo** [comment]
I'll add this as a discussion topic at Wednesday's Collector SIG meeting

**Comment by tigrannajaryan** [comment]
Let's discuss. Perhaps we can come up with some transitional backwards compatibility plan, e.g. receive on both old and new port during a transition period.

**Comment by tigrannajaryan** [comment]
Also, we need 2 ports. OTLP/HTTP uses a [different port 55681](https://github.com/open-telemetry/opentelemetry-specification/issues/1148).

**Comment by Oberon00** [comment]
Why doesn't OTLP/HTTP use the normal HTTP port?

**Comment by tigrannajaryan** [comment]
@Oberon00 technical limitations of Go-based implementation: https://github.com/open-telemetry/opentelemetry-collector/pull/1223

It may be possible to overcome the limitation and I'd highly prefer to use the same port if possible. We have an open issue https://github.com/open-telemetry/opentelemetry-collector/issues/1256 but no known solution yet.

**Comment by tigrannajaryan** [comment]
> Why doesn't OTLP/HTTP use the normal HTTP port?

@Oberon00 I think I misread your question. What do you mean by normal HTTP port? 80/443? They are privileged port numbers and I don't think we want to impose root permissions as a requirement to use OTLP/HTTP.

**Comment by tigrannajaryan** [comment]
Discussed this in TC meeting today. We are going to look into 2 issues before making a decision on this:
- Are we able to have a reasonably painless transition for existing OTLP users (old/new port number support on sending/receiving side). I will look into this.
- Are we able to use one port for OTLP/gRPC and OTLP/HTTP. Depending on this we may need to request registration for 1 port or for 2 ports. @bogdandrutu is going to look into this.

**Comment by tigrannajaryan** [comment]
I had a quick look at the old/new port number support.

- It is not difficult to support receiving on both ports simultaneously in the Collector. We will update the OTLP receiver in the Collector to use a new default. The OTLP receiver will also enable the legacy port receiving when the default configuration is used. This way any users that have the default (omitted) port in the Collector config file will not be affected because of the change of the default port. User that have non-default port in the config likewise won't be affected since the port is explicitly specified. We will keep this dual port receiving for a few months and can retire the legacy port eventually.

- Collector's OTLP exporter currently requires that the destination host and port are explicitly specified. So changing the default port in the OTLP specification has no effect on OTLP exporter in the Collector.

- The SDK exporters have a notion of the [default OTLP port](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/exporter.md#configuration-options), so if we change the default then existing applications/instrumentations will be affected. However, given that vast majority of SDKs are expected to send to the Collector the SDKs will work fine before or after the default port is changed in the SDK _provided that_ the Collector is updated first to the new version which supports receiving on both ports.

- Backends that currently implement may continue using the legacy port number provided that they are receiving from the Collector where that port number is explicitly specified (this should be the majority of use cases). Backends will be however advised to change to the new port or support receiving of both ports like Collector does.

I believe this is sufficient to change the port number without causing pain to current users. Once we have the outcome of the investigation from Bogdan we can move forward.

**Comment by tigrannajaryan** [comment]
@bboreham @mtwo what does IANA registration process require? Do we choose a port number and then apply for registration or we ask for IANA to choose a port number for us first? If it is the former then I assume we just pick something that shows as "Unassigned" in the [IANA list](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt)?

**Comment by mtwo** [comment]
Correct, we can request a specific port or have them auto assign an open one

________________________________

**Comment by tigrannajaryan** [comment]
OK, from what I see 4317-4319 range is unassigned. We can request 4317 and if it turns out OTLP/HTTP needs a separate port then 4318 in addition to that (unless port choices were already made - I don't see anything in this thread).

**Comment by mtwo** [comment]
No choices have been made, I’ll submit the application for 4317 tomorrow morning. Can you answer my question about TXT records? I need to put that in the submission.

________________________________

**Comment by tigrannajaryan** [comment]
@mtwo I do not fully understand what the TXT record is for in the context of port registration. Can you clarify or point me to the relevant part in the port registration RFC? 

Assuming this is the name of the protocol we may need to wait until we have a decision about using 1 or 2 ports. If it is one port we will call it "otlp", if 2 ports then it will be "otlp/grpc" and "otlp/http".

**Comment by mtwo** [comment]
Here: https://tools.ietf.org/html/rfc6763#section-6.1

I also don't understand the purpose of TXT records in this context and I'm not sure why they want them.

**Comment by tigrannajaryan** [comment]
@mtwo this issue was discussed in the spec meeting and the decision is to file for one port now, 4317, named "otlp". The expectation is that most likely one port will be enough and we will not need the second port. If for whatever reason we encounter unexpected problems and need a separate port for OTLP/HTTP we will file for it separately and will give it a different name. cc @bogdandrutu @jmacd

**Comment by mtwo** [comment]
Filing!

________________________________

**Comment by tigrannajaryan** [comment]
Port number change PR in the spec https://github.com/open-telemetry/opentelemetry-specification/issues/1148 and Collector https://github.com/open-telemetry/opentelemetry-collector/pull/2104

**Comment by mtwo** [comment]
Filed the request earlier today: https://tools.iana.org/public-view/viewticket/1182274

**Comment by mtwo** [comment]
@tigrannajaryan the IANA got back to me and there's already a protocol called OTLP that has that same port reserved. I'm guessing that's why you chose it (?).

Would you prefer that drop our request (as there's already a registration for the correct name), or should I ask if there's a way for us to share the port and update the online metadata for the port reservation?

**Comment by tigrannajaryan** [comment]
>the IANA got back to me and there's already a protocol called OTLP that has that same port reserved. I'm guessing that's why you chose it (?).

@mtwo No, I did not know there is already a protocol called OTLP, that's unfortunate :-(

Also, from what I see the existing OTLP at IANA is registered on port 6951, not the port that we proposed (4317).

I am not sure what is the right solution, perhaps we give a different alias name to IANA. We can call it "OpenTelemetry Protocol" and ask for port 4317. We can keep using "OTLP" internally at OpenTelemetry project as an alias of "OpenTelemetry Protocol".

**Comment by mtwo** [comment]
Apologies for the confusion, I mixed up the port numbers. I’ll tell them that our protocol is separate and that we should proceed.

________________________________

**Comment by mtwo** [comment]
Update: they've informed me that we can't use 'OTLP' as our service name as it's already claimed.

Should we proceed with a slightly different name? Just 'OpenTelemetry' perhaps? We could also squat on the claimed otlp port, but that seems like a bad idea and would require an additional port change.

**Comment by carlosalberto** [comment]
What about "OpenTelemetry Protocol"? If not, well, yes, "OpenTelemetry" simply.

**Comment by jkwatson** [comment]
Should implementations hold off on changing default ports until this is resolved? Or is #1221 assumed to be good to go?

**Comment by mtwo** [comment]
Seems reasonable. I’ll tell them to proceed with “OpenTelemetry Protocol”, and we can change the name while the submission is in review.

________________________________

**Comment by mtwo** [comment]
The port itself is good to go! We just need to lock the name at this point

________________________________

**Comment by tigrannajaryan** [comment]
"OpenTelemetry Protocol" sounds good to me. The actual name registered with IANA doesn't really matter that much. The important part of submitting to IANA is that it increases the chance of the port not being used by some other service running locally.

**Comment by tigrannajaryan** [comment]
IANA needs a service name that is no longer than 15 characters. Unfortunately OTLP is already registered by someone else. :-(

Any ideas for a good name? We can go with simply "OpenTelemetry". "OpenTelemetry Protocol" is too long, doesn't fit in the requirements.

**Comment by mtwo** [comment]
+1 for OpenTelemetry

________________________________

**Comment by carlosalberto** [comment]
+1 for OpenTelemetry too.

**Comment by tigrannajaryan** [comment]
OK, going with OpenTelemetry.

**Comment by tigrannajaryan** [comment]
We have a confirmation of [IANA registration](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt):
![image](https://user-images.githubusercontent.com/4194920/101691781-3619ab00-3a3d-11eb-81f9-96b16ef0c4bf.png)

Thank you @mtwo
