### ISSUE TITLE
Define telemetry stability guarantees

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-specification#1301]
It is critical that OpenTelemetry produces telemetry which remains stable. Changes to telemetry produced by OpenTelemetry instrumentation should avoid breaking analysis tools, such as dashboards and alerts. However, it is not clear at this time what type of instrumentation changes (for example, adding additional spans and labels) would actually cause a breaking change.

Related questions:
* What types of changes are known to definitely break the analysis tools which currently target OpenTelemetry?
* Better is always different. If we must make a breaking change in order to offer better instrumentation, what should the procedure be?
* How should we convey changes in telemetry to operators and application owners?
* How should auto-installers handle cases where application owners do not wish to install the latest version of an instrumentation library, in order to manage breaking changes?

Until this issue is resolved, instrumentation packages must not be marked as stable. API and SDK packages may still be marked as stable. The lack of telemetry stability should be clearly communicated in the documentation for every OpenTelemetry client, to avoid confusion.

**Comment by tigrannajaryan** [comment]
# What constitutes a breaking change

For metrics here is an incomplete list of changes that may be breaking for readers of the telemetry (e.g. for dashboards in the backends):
- Renaming of the metric or of a metric label.
- Elimination of a label (dimension) of a metric.
- Introduction of a label to a metric.
- Splitting of a metric into multiple metric across a label dimension.
- Combining of multiple metrics into one metric with an additional label dimension.
- Change of value data type, aggregation or temporality.
- Change of the unit.
- Change of the scale of the values.

For spans:
- Change of the span name.
- Renaming of an attribute.
- Elimination of an attribute.
- Change of the data type of the attribute value.
- Possibly, addition of an attribute.
- Change of an event name or change of an attribute as described above.

For logs: 
- Change of the log record name.
- Renaming of an attribute.
- Elimination of an attribute.
- Change of the data type of the attribute value.
- Possibly, addition of an attribute.
- Change of the body (similar to attribute changes).

**For future discussions I suggest we call the shape and structure of all of the data that is referenced above the _schema_ of telemetry.**

# How we handle the changes

Unlike API, I believe changes described above are more likely to occur during the lifelime of an instrumentation library. I do not think we should aim to lock the telemetry schema and disallow changes listed above. Such locking would place a huge limitation on how instrumentation can evolve and would make it nearly impossible to fix mistakes in the semantic conventions, in the schema or in the implementation of the instrumentation (which _will_ inevitably happen sooner or later).

I suggest that we do the following:

- For 1.0 GA we do not provide stability guarantees for telemetry schema emitted by instrumentation.
- We introduce a formal DSL for defining telemetry schema (for traces, metrics ans logs).
- Telemetry schema should be versioned (independently from API, from SDK and from instrumentation library versions). Over time the schema may evolve and instrumentation libraries may emit data confirming to newer versions of the schema.
- Telemetry schema should implicitly or explicitly define transformations that are necessary to convert telemetry between different schema versions when such conversion is possible. When conversion is not possible it constitutes a truly breaking change - I would like to discuss whether we allow or prohibit this.
- Telemetry emitters (e.g. instrumentation libraries) should include the schema or a reference to the schema in the emitted telemetry.
- Telemetry interpreters (e.g. dashboards on the backend) should pay attention to the schema of the received telemetry. If necessary, telemetry interpreters may transform the telemetry data from the received schema version to the target schema version as expected at the point of use (e.g. a dashboard will define which schema version it expects).
- OpenTelemetry will publish telemetry schema as part of the specification. The schema will be the formalized equivalent of semantic conventions. The schema will be available to be referred and downloaded at well known URLs.
- OTLP will be modified to allow inclusion of the schema or schema reference (URL) in the emitted telemetry.
- OpenTelemetry instrumentation libraries will include the schema URL in all emitted telemetry.
- We will create tooling that validates that emitted telemetry confirms to the declared schema. This can be used by instrumentation libraries in debug builds.
- Possibly, we will implement a processor in Collector that automatically transforms telemetry to a desired target schema version, so that it can be consumed by a backend that does not know how to deal with different schemas.
- Telemetry schema will become available as a concept in one of 1.x releases. Until then OpenTelemetry users should be advised that breaking changes to instrumentation may happen (however, we will try to minimize such changes until the telemetry schemas are introduced).
- Third-party libraries, instrumentation or applications will be advised to define and publish their own telemetry schema and include the schema reference in the emitted telemetry.

I can put together an OTEP that describes this proposal in more details.

FYI, @open-telemetry/specs-approvers

**Comment by tedsuo** [comment]
Thanks @tigrannajaryan. After more conversations I agree. We should issue a v1.0 without these data guarantees. We can't even begin to address this until everything else in tracing and metrics is complete. I've removed the `required-for-ga` label.

**Comment by Oberon00** [comment]
Should we give this priority for the next GA release? It might have slipped through so far because it has the `spec:metrics` label on it.

**Comment by tigrannajaryan** [comment]
@Oberon00 I believe we should. I am going to work on https://github.com/open-telemetry/opentelemetry-specification/issues/1324 in the next few weeks. I need to do some experimentation but I hope it will be the answer to this issue as well.

**Comment by tigrannajaryan** [comment]
Assigning this to myself since I plan to work on a very related issue.

**Comment by tigrannajaryan** [comment]
Related reference from k8s about metric stability: https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#metric-lifecycle

IMO, k8s is not fully solving the problem, but rather makes it manageable, creates clarity in the deprecation process and slows it down appropriately to give affected parties time to react. While certainly an improvement over just making breaking changes I think we need to go in a different, more promising direction: https://github.com/open-telemetry/opentelemetry-specification/issues/1324

**Comment by NathanielRN** [comment]
@tigrannajaryan Is there an issue to add schemas to the specification now that https://github.com/open-telemetry/oteps/pull/152 is merged? Otherwise, what is the next step for it?

I see we already have this folder: https://github.com/open-telemetry/opentelemetry-specification/tree/main/schemas so does that mean the OTEP is adopted?

**Comment by tigrannajaryan** [comment]
Yes, OTEP is adopted and relevant bits are added to the spec, e.g. [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer) or [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#create).

**Comment by tedsuo** [comment]
@tigrannajaryan in that case, can this issue be closed?

**Comment by tigrannajaryan** [comment]
Yes, I think we can close this. We will create new issues for any follow up tasks/problems as needed.
