### ISSUE TITLE
Rename OTEL_METRICS_EXPORTER to OTEL_METRIC_EXPORTER

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#1353]
Realized that our OTLP metrics exporter uses `_METRIC_` rather than `_METRICS_` in its environment variables, as [seen here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/exporter.md#configuration-options).

IMHO it makes sense to rename the newly added `OTEL_METRICS_EXPORTER` to match that pattern (or as alternative use the `_METRICS_` pattern for the OTLP exporter).

cc @anuraaga

**Comment by anuraaga** [comment]
Sorry for missing the gap with the other variables. I'd take the same pick as #1352 - trace corresponds with metrics, span corresponds with metric...I think? Well I guess we also call the exported stuff a point, not a metric. I lean towards trace / metrics since the names are least ambiguous, they're the name of the signals which are used in a lot of places in the spec / docs.
