### ISSUE TITLE
Define the default value for null/empty instrumentation-name

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#1472]
Currently [TracerProvider.GetTracer()](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer) is defined as:

> In case an invalid name (null or empty string) is specified, a working default Tracer implementation as a fallback is returned rather than returning null or throwing an exception.

However, different SIGs have different values, i.e.

* Java uses `unknown`
* JS uses the empty string
* Python uses `ERROR:MISSING MODULE NAME`

I'd suggest we define a SHOULD on this, so at least the default is (more or less) shared. Personally I'd go with `unknown` (although defaulting to "" probably would be helpful if we ever support a _default_ `Tracer`, i.e. `TracerProvider.getDefaultTracer()`)

**Comment by arminru** [comment]
Good catch! I think we should definitely go for a consistent fallback here.
Personally I like Python's fallback since it clearly points out that this an undesirable state and just used for gracefully handling a missing or invalid parameter rather than being a valid, intended default value.

What about `<INVALID NAME PROVIDED>` or something like that?
It should be clearly distinguishable from valid values provided by users (who would usually pass `this.class.name` and such).

As for a `getDefaultTracer` or `getApplicationTracer` that we might consider adding in future, I'd go for a different value there, probably even an empty string.

**Comment by arminru** [comment]
I also think this should only affect the SDK spec and not be mentioned in the API spec as well as the resulting interface definitions in the implementations. This is not something one should rely on. The API spec should only define what is valid as input for this method and if this is not complied with, it's undefined behavior from an API perspective.

The entire sentence
> In case an invalid name (null or empty string) is specified, a working default Tracer implementation as a fallback is returned rather than returning null or throwing an exception.

should've been only mentioned in the SDK spec IMHO but we'll have to leave this one in now.

**Comment by Oberon00** [comment]
I would vote for `<INVALID INSTRUMENTATION NAME PROVIDED>`. It's OK if its very long, you should only see it shortly until you fix it anyway 😃

By the way, as commented in https://github.com/open-telemetry/opentelemetry-specification/issues/586#issuecomment-669856711, "working default tracer" could be interpreted as no-op tracer so we should maybe clear that up too.

**Comment by carlosalberto** [comment]
Trying to re-awake this: I'd vow for going with `unknown_instrumentation_name`, trying to stay in line with what `Resource` does in absence of `service.name`.

In any case, assigning this to me to get ourselves moving ;)
