### ISSUE TITLE
Distinction between structured `Body` and `Attributes`

### ISSUE THREAD

**Issue by jmm** [open-telemetry/opentelemetry-specification#1613]
Is there a clear distinction between what belongs in a structured `Body` vs. in `Attributes`? If there's not, it seems to make it less predictable where data is expected, and how to map between other models.

A top-level "message" string seems to be pretty common among other log data models. In this model, if you want to have a top-level message string and structured data describing the event, are you supposed to put the message in `Body` and other data that would otherwise be in `Body` in `Attributes`? I don't see anything about special-casing a property of `Body` as a top-level message.

From the mapping perspective, considering the Elastic Common Schema (ECS) example, it doesn't include all ECS fields, but `message` is the only one shown as mapping to `Body`. `Body` seems like a logical (perhaps the most logical) place for fields like `error.message` or `event.id`. So the fact that fields like `error.message` are shown as mapping into `Attributes` makes it seem that there's not a clear distinction, and that the mapping could be ambiguous depending on whether `message` is populated.

(BTW, unlike most of the rest of the document, the ECS example refers to "body" and "attributes" rather than "Body" and "Attributes", which I assume is a typo or holdover from a previous version.)

---

`Attributes` is documented as:

> SHOULD follow OpenTelemetry semantic conventions for Attributes.

If I understand correctly, that means that a property of `Attributes` that has the name of a well-known attribute should have the meaning and data type defined for that attribute, but meanwhile `Attributes` can also include arbitrary custom attributes.

That also seems to have implications for placement of data within `Body` vs. `Attributes`, because whereas no semantic conventions apply to `Body`, if a property gets bumped from `Body` into `Attributes`, then it may be that conventions are supposed to apply that wouldn't otherwise.

**Comment by pmm-sumo** [comment]
I personally see no reason to create another container for key/values associated with Log Record. If something is not covered by semantic conventions, it simply means that it's definition is out of scope of OT - it might be related to a given environment, come in MDC, etc. As long as there's no conflict in the key names, why we cannot reuse Attributes?

**Comment by jmm** [comment]
Thank you both for commenting.

What I was really wondering is if it would make the most sense to have a top-level `Message` that's always a string when defined, and structured data that's part of the event would always go into a map in a top level property such as `Attributes` (perhaps under a key reserved for a nested map of custom data with no semantic conventions?), or perhaps a top-level map reserved for that data (though maybe that clashes with reserving top-level properties for things that are almost always present).

Maybe I misunderstood, but I got the impression @pmm-sumo was suggesting that any structured data that could currently be placed in `Body` could instead go in `Attributes`, instead of `Body` sometimes containing structured data, which is part of what I was getting at. By "another container" did you mean `Body` or `Context` from #1660?

**Comment by pmm-sumo** [comment]
I think I messed up and my comment was largely referring to `Context` of #1660 (somehow I mixed up the two issues). Apologies for that @jmm!

In either case, what I wanted to say is that the more I look at it, the more I feel that having ability to put key-values into `Body` is somewhat redundant since we have `Attributes`

I think we may also want to change perspective when looking at that. Let's consider that both `Body` and `Attributes` contain key-values. Does it make any practical difference from processor, exporter or vendor perspective if a given key-value is present in `Body` or in `Attributes`? 

The only case I can think of if someone wants to put a boundary between metadata (present in `Attributes`) and record content (which might be a structured `Body`), so there would be a clear distinction between those. 

To bring an example, consider someone is having a temperature sensor and logging its output. The sensor has some metadata assigned, e.g. id, connection type, etc. that are not part of the record. Practically, this might look like following:
```
Body: {"temperature": 21.4, "unit": "degrees_celcius"}
Attributes: {"sensor_id": "1a90c", "manufacturer": "Acme", "connection": "usb 3.2"}
```

**Comment by jmm** [comment]
@pmm-sumo no worries!

> The only case I can think of if someone wants to put a boundary between metadata (present in `Attributes`) and record content (which might be a structured `Body`), so there would be a clear distinction between those.

Yeah that's what I was getting at. But the way it's designed currently, any time you want to have structured record content _and_ a top-level message, the structured content would have to be bumped into `Attributes` anyway. Unless the idea is that message and structured record content are mutually exclusive. And the example mapping of ECS to this model shows data that I see as part of the event, and therefore probably most at home in `Body`, being mapped into `Attributes`.

**Comment by pmm-sumo** [comment]
> Unless the idea is that message and structured record content are mutually exclusive. 

My understanding of [`Body` field description](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-body) is exactly that - either a raw message or a structured content (map or array). This is further reinforced by [`any` type definition](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#type-any)

**Comment by jmm** [comment]
Right, it's mutually exclusive in terms of `Body`. But if you populate `Body` with a message string, is that supposed to mean you can't also populate arbitrary structured data that doesn't have standardized semantics? If that's not the intent then the structured data would have to get bumped into `Attributes`, right? Let's say a message and tags, for example. 

So what I'm really wondering is if things would be more straightforward by having a top-level `Message` that's always a string when populated, and additional structured data without standardized semantics would always go within a certain top-level property (whether it's under `Attributes` or `Body` or something else).

**Comment by pmm-sumo** [comment]
> But if you populate `Body` with a message string, is that supposed to mean you can't also populate arbitrary structured data that doesn't have standardized semantics?

I believe they can hold any sort of data. They SHOULD (not MUST) follow Semantic Conventions according to the [data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-attributes). 

Lets consider several options:

1) `Attributes` only
My understanding is that it's much like ECS schema. There is a special key, say `Message` that denotes an attribute containing raw string message. If the message is structured, the related fields are mixed with metadata

2) `Attributes` and `Message` 
This is the same like above, except Message is now a field of the record. Everything else holds true

3) `Attributes`, `Message` and `MessageAttributes` (for a lack of a better name)
Let's say we want to separate record-level attributes and message-level attributes (if the original message was structured). That's one way to do it. 

4) `Attributes` and `Body`
This is the current approach. Body is flexible enough to cover either a structured original message or a plain-text original message but not really both (unless some standard field name would be introduced for plain-text message).  

For a practical example, here's a random output from OpenTelemetry Collector:
```
2021-05-06T21:43:23.740+0200	info	service/application.go:261	Starting OpenTelemetry Collector...	{"Version": "v0.24.0-27-gfa73baf8", "GitHash": "fa73baf8", "NumCPU": 16}
```

What I am wondering about is following. Taking the timestamp, log level and component aside, we end up with essentially a message: `Starting OpenTelemetry Collector...` and some attributes: `{"Version": "v0.24.0-27-gfa73baf8", "GitHash": "fa73baf8", "NumCPU": 16}`. With the current approach, should they land in `Attributes` or as a part of a structured `Body`? If it's the latter, what about the message?

**Comment by tigrannajaryan** [comment]
@jmm @pmm-sumo let's discuss today in Log SIG meeting if you plan to attend.

**Comment by tigrannajaryan** [comment]
What do you think about the following?

-----
If the log record contains one or more "pieces" of data that may fit either in Body or Attributes but do not fit the description of the other top-level fields (Timestamp, Severity, etc) then follow these guidelines to decide how to record these pieces of data in the Body and Attribute fields:

1. If the log record contains a single raw byte sequence that is not associated with any particular key (such that we cannot think of it as a key/value pair) put it in the Body.
1. If the log record contains a single raw Unicode character string that is not associated with any particular key then put it in the Body.
1. If the log record contains a single JSON-like array value or a primitive value that is not associated with any particular key then put it in the Body.
1. If the log record contains a single JSON-like object with key/value pairs it may be recorded either in the Body or in the Attributes. The choice in this case should be based on whether we are interested in individual key/value pairs (e.g. each key/value has a particular meaning, possibly independently from the meaning of the other key/value pairs), in which case recording them in the Attributes would be preferable. Otherwise if we are more interested in just recording the object as a whole and getting it delivered then the Body would be preferable.
1. If the log record contains a piece of data that is associated with a key then record that piece as a key/value pair in the Attributes.

Note: if there is more than one piece of data that matches the rules 1-4 then we cannot record then in the Body, we have to come up with some keys and record each piece of data as a key/value pair in the Attributes.

-----

This is a non-exhaustive set of heuristics but should be probably a good starting point. What do you think?

**Comment by pmm-sumo** [comment]
@tigrannajaryan @djaglowski sure, preparing a proposal

**Comment by pmm-sumo** [comment]
We had great discussion but reached no consensus on neither #1727 (providing guidelines) nor #1752 (be more restrictive). It is currently one of the major ones blocking Logs GA. Perhaps we could sync during the next Log SIG and discuss it online? 

The next Log SIG is scheduled Oct 27th, 10am Pacific, though we suggest to move it a week earlier, Oct 20th, same time. If that time does not work, we could organise a dedicated sync for that issue. 

Would that work for you? @yurishkuro @SergeyKanzhelev @errordeveloper @tigrannajaryan @djaglowski @jmm

**Comment by yurishkuro** [comment]
the question in chat was this (with my emphasis):

> Knowing that the body on logs can be a structured data, *when should one be using* the body to provide additional attributes instead of using the attributes from the log record itself?

I think the problem we're having is we are not clear about who is this "one". Which persona is that? An application developer using a logging API from an application? Or an infrastructure engineer writing a transformation of one data format into OTLP? These are distinct use cases requiring distinct solutions.

Having said that, I like the suggestion in https://github.com/open-telemetry/opentelemetry-specification/pull/1727/files#r643105246 of restricting Body to be a primitive type. I think it resolves the confusions without limiting the expressiveness of OTLP model.

**Comment by tigrannajaryan** [comment]
>I think the problem we're having is we are not clear about who is this "one". Which persona is that? An application developer using a logging API from an application?

Yes, I think the confusion primarily arises when one needs to generate a log record (via a logging API or emit an OTLP log record). This is a clean slate situation: I know I want to generate a log record, I know roughly what data I want to put in the record, but I can structure the same data such that some _primary_ bit goes into the Body (e.g. the human readable message) and the rest goes into the Attributes or I can put everything into Attributes (with the human readable message being just another Attribute). In other words one can also say that it is a data modelling problem: given some information I know I want to record and having ability to record it in a few different ways how do I make a decision about the shape I want this information to take?

>Or an infrastructure engineer writing a transformation of one data format into OTLP?

This likely is not an issue, since it is primarily driven by the semantics of that particular data format. We have examples of transformations in the [log data model doc](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#appendix-a-example-mappings), a few of which I wrote and I think it was fairly straightforward to know what to put in the Body vs Attributes.

> Having said that, I like the suggestion in https://github.com/open-telemetry/opentelemetry-specification/pull/1727/files#r643105246 of restricting Body to be a primitive type.

I don't think that will work. There are formats where log body is a complex structured data (there are a couple examples in log data model doc).

**Comment by yurishkuro** [comment]
To put it differently, if they haven't solved the semantic distinction between structured body and attributes (and they sit much closer to user intent), how can we expect to solve it downstream of them? I would instead be inclined to change the mapping tables you linked to and say that those structured fields do NOT map to Body, but to similarly named attributes, like `json_payload` (especially if it helps to change Body field to a primitive type).

**Comment by yurishkuro** [comment]
Ok, but it seems the only reason we have body as structured field is to support these mappings from 3rd party formats. With respect to this ticket, we can easily say "we recommend treating body is a string", and only treat body as structured when doing those 3rd party conversions.

**Comment by djaglowski** [comment]
> Unless someone objects I suggest to close this issue since the 4 above capture the totality of the work to be done.

Shall we close this?
