### ISSUE TITLE
Remove hasRemoteParent from Sampler.shouldSample method

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-specification#164]
Created from https://github.com/open-telemetry/opentelemetry-java/pull/430#discussion_r297311630

> I think we should remove this for the moment because no clear use for this. I think what we should add support later is a notion of "untrusted parent". But probably that needs a RFC. So I would suggest we file an issue on the specification to remove this.

https://github.com/open-telemetry/opentelemetry-java/blob/ed42237b6c71052bbffe4d849647c53fae81b246/api/src/main/java/io/opentelemetry/trace/Sampler.java#L44-L50

cc @bogdandrutu

**Comment by bogdandrutu** [comment]
To clarify a bit the comment: I am proposing to remove the hasRemoteParent from the Sampler interface because with the latest changes in the SpanBuilder, a child Span can be started with a SpanContext as parent even if the parent is not remote, so we cannot determine correctly if the parent is remote or not.

**Comment by jmacd** [comment]
I admit lacking some of the details that went into the current Java prototype, but on the topic of Sampler API, I have questions. Why is this considered `area:API`? I see this as an SDK interface. The SDK supports an API for sampling, but it is distinct from the end-user instrumentation API. 

Rationale: a user never interacts directly with the Sampler. 

Should this be classified `area:SDK`?

**Comment by bogdandrutu** [comment]
@jmacd it cannot be in the SDK because users need this when instrumenting their applications. Imagine using the OpenTelemetry with an implementation that does upfront sampling and for some specific requests users always want to be sampled. If the Sampler is in the SDK they need to depend on the SDK to be able to specify that for this particular request/Span I always/never want sampling.

I think this behavior should be supported in the API to avoid users start depending on a specific implementation.

**Comment by z1c0** [comment]
For our sampling implementation, a fine-grained sampling API would not be a good fit.
An opinionated sampler implementation should be able to make this decision for itself.
A slim API (e.g. a hint or recommendation) would be a good compromise.

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu assigning to you as you are working on moving sampling to SDK and related changes

**Comment by jmacd** [comment]
Closing this for now as there are a number of in-flight and unaccepted issues/PRs about sampling. This is stale.
