### ISSUE TITLE
Add semantic convention for describing graphql spans

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry-specification#1670]
**What are you trying to achieve?**
>GraphQL is an open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data. [...] GraphQL servers are available for multiple languages, including Haskell, JavaScript, Perl, Python, Ruby, Java, C++, C#, Scala, Go, Rust, Elixir, Erlang, PHP, R, D and Clojure. ([Source: Wikipedia](https://en.wikipedia.org/wiki/GraphQL))

There are already graphql instrumentation libraries for Node.JS and Ruby (https://opentelemetry.io/registry/?s=graphql) and as quoted above there could be many more. GraphQL has a [specification](https://spec.graphql.org/June2018/) that could be used to define span attributes. For example the Node.JS instrumentation defines the following:

```
export enum SpanAttributes {
  COMPONENT = 'graphql',
  SOURCE = 'graphql.source',
  FIELD_NAME = 'graphql.field.name',
  FIELD_PATH = 'graphql.field.path',
  FIELD_TYPE = 'graphql.field.type',
  OPERATION = 'graphql.operation.name',
  VARIABLES = 'graphql.variables.',
  ERROR_VALIDATION_NAME = 'graphql.validation.error',
}
```

The most important ones would be the operation name (query, mutatation, ...) and if available the query name.

**Comment by ericmustin** [comment]
Was there any reason this stalled? The stronger we can make the semantic conventions around instrumentation attributes, the better, especially for these details which are already implemented across multiple languages?

**Comment by spencerwilson** [comment]
Just want to point to these two issues folks raised in JS that involve GraphQL semconv:
- https://github.com/open-telemetry/opentelemetry-js-contrib/issues/534
- https://github.com/open-telemetry/opentelemetry-js-contrib/issues/705

I don’t see any acute reason this should be blocked, so I assume it’s stalled simply for lack of someone making a PR.

**Comment by jord1e** [comment]
I can look into contributing a PR this weekend, some prior art to be looked at is the Apollo schema reporting Protobuf file (https://github.com/apollographql/apollo-server/blob/e468367d52e11f3127597e4fe920eb8294538289/packages/apollo-reporting-protobuf/src/reports.proto)

And of course the standing opentelemetry-js(-contrib) and opentelemetry-ruby conventions

Some input from the [GraphQL Working Group](https://github.com/graphql/graphql-wg) may also be useful (do companies use Apollo Query Ids, should they be added as a Span attribute?, should we add the query name as an attribute?)

**Comment by spencerwilson** [comment]
Something I'm unsure whether should be in scope of GraphQL semantic conventions, but suspect might be: For a GraphQL server, there are many distinct procedures that might deserve getting their own span, depending on one's telemetry requirements. Some of them include:

- parse the given string as an [ExecutableDocument](https://spec.graphql.org/October2021/#ExecutableDocument)
- run [validation](https://spec.graphql.org/October2021/#sec-Validation) on the parsed document
- [execute](https://spec.graphql.org/October2021/#sec-Execution) an operation in the document (a document may contain multiple OperationDefinitions, but during document execution at most one of the operations defined within is executed)
  - [ExecuteField](https://spec.graphql.org/October2021/#ExecuteField()): Encompasses getting the complete return value for a field and any selection set on it
    - [ResolveFieldValue](https://spec.graphql.org/October2021/#sel-FANRFCDHAACJAuuc): When the function associated with a field is run.
    - [CompleteValue](https://spec.graphql.org/October2021/#sel-GANRFCJCAACCBntM): Either lightweight "finishing" logic (if the current field's type is of kind Scalar or Enum, or a List or Non-Null wrapping thereof), or one or more field executions otherwise (resolving the selection set on the field)

I've not reviewed all existing GraphQL OTel instrumentations to see which of these procedures get their own span. The only one I've reviewed is  the JavaScript instrumentation ([repo](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/e3ce1029914b4bb4715a644629b9b86c76b9f007/plugins/node/opentelemetry-instrumentation-graphql)), in which the following procedures get spans ([src](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/e3ce1029914b4bb4715a644629b9b86c76b9f007/plugins/node/opentelemetry-instrumentation-graphql/src/enum.ts#L49-L54)):

- `parse` and `parseSchema`: These spans are produced by wrapping the `parse` function exported from [graphql-js](https://github.com/graphql/graphql-js/tree/v16.2.0)
- `validate` and `validateSchema`: Produced by wrapping the `validate` function exported from graphql-js
- `execute`: Produced by wrapping graphql-js's `execute` function. As of graphql-js@16.2.0 this function is only to be used for operations of type _query_ and _mutation_, but eventually it will be the supported way of executing _subscription_, too ([src](https://github.com/graphql/graphql-js/blob/v16.2.0/src/execution/execute.ts#L389-L392)).
  - Corresponds to [ExecuteRequest](https://spec.graphql.org/October2021/#ExecuteRequest()) in the spec, but notably due to the aforementioned implementation detail, the GraphQL instrumentation currently only creates `execute` spans for queries and mutations, not for subscriptions.
- `resolve`: Produced by mutating the schema object to wrap any application-provided resolver functions.
  - Corresponds to [ResolveFieldValue](https://spec.graphql.org/October2021/#ResolveFieldValue())

My motivation to go into this detail here is that as a user of the graphql-js auto instrumentation, I've at times found myself wishing that I had spans for ExecuteField, i.e., something representing ResolveFieldValue (individual resolvers running) + CompleteValue (encompassing all recursive resolution).

The relevance to semconv, minimally, is: How should these different procedures be indicated on the Span data model? My intuition suggests they should be codified at least as some span attribute (if not also a component of span name), but I haven't read all the existing semconv to know if that's best—or if there's an obvious right answer that already exists, for that matter.

---

Also want to mention the following which might be helpful references, if we're ever seeking definitions for things, see:
- a WIP [Glossary](https://github.com/graphql/graphql-wg/blob/ea2f3e82385574eb5bddf546bc965f74245ea53b/rfcs/glossary/Appendix%20C%20--%20Glossary.md) in graphql/graphql-wg
- the GraphQL spec (naturally). Some definitions will be indicated with Spec Markdown's [definitions](https://github.com/leebyron/spec-md/blob/19ccf5f229d0efa2f89157a2d17ca4451add1f31/spec/Spec%20Additions.md#definitions) syntaxes, but it looks like that's relatively recent so there are surely plenty of definitions which aren't yet syntactically indicated as definitions.

**Comment by tigrannajaryan** [comment]
Done in https://github.com/open-telemetry/opentelemetry-specification/pull/2456
