### ISSUE TITLE
No mention of dropped attributes/events/links counts in SDK spec

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-specification#1698]
The exporter spec defines how to handle DroppedAttributesCount and DroppedEventsCount (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/non-otlp.md#dropped-attributes-count) at export time, but it isn't clear from the SDK spec that these should be reported.

**Comment by reyang** [comment]
Some follow up items:
@jsuereth instead of reporting it as key-value pair (attribute), we might need to allow vendors to report this directly. There is already one for traces/events/logs, there is an issue opened to add this to the metrics OTLP.
@jmacd this is not the identity of the span, it is part of the collection (what happened at collection time).
