### ISSUE TITLE
Replace tracer format methods with `inject` and `extract`

### ISSUE THREAD

**Issue by rochdev** [open-telemetry/opentelemetry-specification#174]
Right now there are `getHttpTextFormat` and `getBinaryFormat` defined on `Tracer`. These are inflexible as they don't allow extensions without vendor lock-in by requiring the users to use  an external class directly as it cannot be dynamically added to the list of supported formats.

Having single `inject` and `extract` methods for all formats on `Tracer` similar to OpenTracing would allow adding formats without changing the API. This would apply to formats added by OpenTelemetry, vendors, and users.

I proposed this in JS but it was [rejected](https://github.com/open-telemetry/opentelemetry-js/pull/85/files#r300810012) as it's incompatible with the spec, even though the current API could very easily be replaced by the above which would be a lot cleaner.

**Comment by bogdandrutu** [comment]
Not sure I understand how can you add new capabilities without changing the API, at least even in the OpenTracing API which I suppose you refer to there is an enum which needs to change when adding a new format. If you do use a String for the format that is very unsafe because the type may not be supported.

So the argument that the API does not change is weak, and having the type defined by a string has a lot of problems as well.

Imagine if someone writes a code where they call inject with `format = foo`, if the format is not well define this is a definition of vendor locking. By having well defined formats we actually avoid vendor locking.

**Comment by rochdev** [comment]
> If you do use a String for the format that is very unsafe because the type may not be supported.

In JavaScript an enum is a string or a number, so this argument about type safety is completely invalid. My understanding is that this is a cross-language specification so it shouldn't have Java-centric requirements. In JavaScript this type of pattern is very common to allow extensibility. We currently use this functionality of OpenTracing in our own tracer to stay 100% compliant.

> if the format is not well define this is a definition of vendor locking

The argument was about vendor lock in based on the API. If I switch to a vendor that doesn't support a format that is defined as a string, it will only break propagation. If I need to add a method to add a format and then the user is required to use that method, then when they change vendor the code will actually break. This means that in the first scenario there is no lock in as you can freely change vendor without causing your code to completely break. For the purpose of OpenTelemetry, this extensibility could be used by specific vendors to implement their own formats that could be registered with the tracer and would be ignored by the others. While there could be the argument that these additional formats should be added to OpenTelemetry, this is not always possible as it may be very specific to a single vendor.

**Comment by bogdandrutu** [comment]
Not sure I understand, defining these types in the API seems to have the same effect, vendor that does not support one of the types will return a no-op for that and code is not going to break. Probably you have different scenarios in mind which I do not think of.

By allowing a string I think it is worse because there is no standard for the string and vendor FOO can say I support type BAR which is only supported by that specific vendor.

**Comment by tedsuo** [comment]
This issue is stale, but work has continued in this OTEP: https://github.com/open-telemetry/oteps/pull/66

Closing for now.
