### ISSUE TITLE
otlp default endpoint port for http is different from collector receiver default

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-specification#1920]
[According to the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options), the default value for `Endpoint (OTLP/HTTP)` is `https://localhost:4317`, However, [the collector default listening port for otlp over HTTP is 4318](https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver#getting-started):

> endpoint (default = 0.0.0.0:4317 for grpc protocol, 0.0.0.0:4318 http protocol)

Should the spec change the default endpoint port for OTLP/HTTP from 4317 to 4318 to be synced with the collector's port?

**Comment by Oberon00** [comment]
It seems like this is a recurring problem, we had a similar issue in #1816.
CC @tigrannajaryan

**Comment by tigrannajaryan** [comment]
This is an unfortunate result of moving back and forth on the decision to have a single port or 2 separate ports. Collector currently has 2 ports but there is a draft PR which tries to combine them according to the spec.

We can change change the spec to match the reality for now and then if we are able to merge the ports in the Collector amend the spec again. The SDKs are/will likely use different ports and changing a default port is a breaking change so I am not sure if this is a good idea. I don't know how to nicely handle this so that it is not a breaking change. On the Collector side we can make the OTLP receiver accept data on both ports even after the port merging is implemented, but that doesn't help other receivers (e.g. backends).

Any thoughts on how to make this transition without breaking stuff?

**Comment by carlosalberto** [comment]
As we have mentioned, at Lightstep we had a few problems using a single port for such functionality, and I'd rather have a unified port as a _feature_ (if the prototype proves it's all good). That would be a rather conservative position, but probably it's a good position at this time.

**Comment by carlosalberto** [comment]
@tigrannajaryan any though after it was mentioned that https://github.com/open-telemetry/opentelemetry-collector/pull/3765 may not receive enough iterations in the near future?

**Comment by tigrannajaryan** [comment]
I think given that we heard using one port caused pains for others in the past and given that we do not have an existing Collector implementation that uses one port and do not have anyone with experience who can contribute an implementation that uses one port we should stop pursuing one port and go with 2 ports.
Collector already uses 2 ports, it works and is known to not have any problems. I do not think it is very important to have one port and risk having problems down the road.

The SDK exporters and any other OTLP senders must choose the transport (gRPC or HTTP) anyway. When this choice is made the senders can also choose the correct port, so it is not additional burden for the end user.

Unless anybody has strong objections I suggest that we keep the ports separate.

**Comment by tigrannajaryan** [comment]
I also raised this in the Maintainers meeting and did not hear any objections to my suggestion to keep the ports separate.

**Comment by tigrannajaryan** [comment]
PR submitted to split the ports in the spec: https://github.com/open-telemetry/opentelemetry-specification/pull/1970
