### ISSUE TITLE
gzip compression support in OTLP receivers

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-specification#1937]
After discussing #1895 during this week's Spec SIG call, we realized JS/mobile platforms truly require gzip compression by default.

So we have the following options when it comes to the OTLP receivers:

A) OTLP receivers (gRPC, http/protobuf, http/json) MUST handle the officially supported compression formats (gzip only at this moment).
B) OTLP receivers MAY support compression (only gzip at this moment), and they should return a specific error code in case they don't support it. I think this is the path you wanted, and I just wanted to confirm (we would need to choose what code, among https://godoc.org/google.golang.org/grpc/codes, to go with).

cc @bogdandrutu @dyladan @tigrannajaryan

**Comment by tigrannajaryan** [comment]
I am not sure I understand why we have both A and B. It seems like it should be either MUST or MAY, it cannot be both.

**Comment by tigrannajaryan** [comment]
@carlosalberto please clarify the difference between A and B.

**Comment by dyladan** [comment]
I think if we go with A then a client can know that gzip will be supported. If we got with B then the client can try gzip and if it fails with a very specific error code the client can then disable gzip and retry (and send all further messages without gzip)

**Comment by jack-berg** [comment]
Isn't this already resolved? The spec [says](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/protocol/otlp.md#L78) server components MUST support gzip. 

#1895 was [closed because](https://github.com/open-telemetry/opentelemetry-specification/pull/1895#issuecomment-959861222) the defaults for SDKs are aimed at exporting a collector running as an agent on the same host, where compression will probably hurt instead of help. 

The collector, where the default config isn't aimed at exporting to a local process, already takes advantage of the gzip requirement by exporting with gzip [by default](https://github.com/open-telemetry/opentelemetry-collector/blame/main/exporter/otlpexporter/README.md#L40).

**Comment by tigrannajaryan** [comment]
> Isn't this already resolved? The spec [says](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/protocol/otlp.md#L78) server components MUST support gzip.

I assume this is what this issue is about and it is now resolved. Closing. Please reopen if this issue is about something else.
