### ISSUE TITLE
Clarify version compatibility with API and SDK packages

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2018]
The [versioning](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md) document says that:
>The API, SDK, Semantic Conventions, and contrib components have independent version numbers.
For example, the latest version of `opentelemetry-python-api` MAY be at v1.2.3 while the latest version of `opentelemetry-python-sdk` is at v2.3.1.

However, it does not define any further compatibility requirements between API and SDK (as far as I can see). I believe we need to define what happens if:
- API is a newer version and the SDK implements an older version of the API. For example the new version of the API may define a new function. What happen if this function is called and there is no implementation for it in the SDK? For compiled languages this likely will be a compilation error, unless API specifically implements dynamic binding - in which case the question is what happens during the call. Also, what's the expectation from dynamic languages where this will likely only get detected at runtime?
- API is older version and SDK implements a new version of the API. Presumably this is fine and we expect the SDK to behave according to the old API's behavior. We should probably call this out explicitly.

**Comment by iNikem** [comment]
@anuraaga Your argument breaks the moment auto-instrumentation enters the room :) We specifically discussed that Java instrumentation wants to support a use-case when application or library used by the application uses OpenTelemetry API which is older that the SDK brought by javaagent.

**Comment by anuraaga** [comment]
@iNikem Auto instrumentation is complicated so wasn't sure to mention it here (what happens in auto instrumentation stays in auto instrumentation? :P). Auto instrumentation doesn't have any compatibility issue of API and SDK really, it's API in app vs API in agent. Conceptually it is similar to being app=API and agent=SDK though, in which case yes we follow the pattern of SDK newer than API is allowed. But it's implemented inside an API bridge rather than anything in the SDK and we don't expect the SDK repo to have any extra requirements related to this, it's all the job of the agent.

**Comment by jkwatson** [comment]
There are two things to consider here, @obecny . One is the version of the API that a library depends on, and the other is the version of the API that is depended on by the SDK at *runtime*.  

So, imagine this case:
* library X is instrumented using API library version 1.6.
* Application A uses library X, and hence has a transitive dependency on API library version 1.6
* Application A uses the SDK, and runs at version 1.9. 

It is entirely appropriate, using standard Java dependency mechanisms, for the SDK dependency to require that the 1.6 API dependency version be upgraded to 1.9 build time of the Application. 

What isn't appropriate, or allowed, is for the library instrumentation (which was written against v1.6) to break under these circumstances. Indeed, it *must* continue to work, even if the SDK upgrades it's API version to something greater than 1.6, in the 1.x version series.

**Comment by yurishkuro** [comment]
@obecny the SDK must put an upper bound on the API version it understands, e.g. `otel_api >= 1.0, < 1.1`.  If an application is built with 1.1 API then it should fail dependency resolution trying to bind the SDK since it does not allow API 1.1, only 1.0. Once the SDK is validated that it satisfies API 1.1, it will release a new version with new bounds `otel_api >= 1.0, < 1.2`.

**Comment by iNikem** [comment]
> Api introduced a new function or new interface property called "test".
> This new functionality will be calling or reading the property from SDK.

@obecny you got me confused here. How API can call SDK? API cannot depend on SDK, right?

**Comment by obecny** [comment]
> > Api introduced a new function or new interface property called "test".
> > This new functionality will be calling or reading the property from SDK.
> 
> @obecny you got me confused here. How API can call SDK? API cannot depend on SDK, right?

api is exposing interface for example `ContextManager`. Then api exposes a function for registering this context manager. Then later you can call from instrumentation for example
`api.context.active()`
this will return the active context.
When user calls this the api will be calling some functionality from registered ContextManager.
So this is the moment when api calls functionality from different components.
You will have here the same, let say we add new function to interface `ContextManager` and what should happen when user then calls this new function and lest say the registered `ContextManager` will not have it yet.
I don't have any strong opinion on any solution, I just want to make sure we say it clearly how to handle such scenario, what will be possible and what not etc. etc. so that it will be clear for everybody.

**Comment by iNikem** [comment]
> @Rauno56 that's a nice example. In contrib repo we have many plugins plus let's consider also a 3rd party plugins - that means quite a lot of plugins. Now let's say 1 plugin has been updated to use latest sdk 1.1.x and other not. Does't it mean that plugin 1.1.x will never be compatible with any plugin from 1.0.x ? So if you are using a number of plugins you would have to wait now for all of them to be finally updated to 1.1.x even though they will not use any new functionality etc. ? Should we allow to use plugin 1.1.x with 1.0.x together or not ?

@obecny What `plugins` exactly are you talking about here? If they are e.g. http client or any other integration with some library or framework, then they are "users" and should only use API. And then during any given runtime you can mix and mach users of both 1.0.x and 1.1.x version of API as long as you configure SDK version 1.1.x.

**Comment by obecny** [comment]
> > @Rauno56 that's a nice example. In contrib repo we have many plugins plus let's consider also a 3rd party plugins - that means quite a lot of plugins. Now let's say 1 plugin has been updated to use latest sdk 1.1.x and other not. Does't it mean that plugin 1.1.x will never be compatible with any plugin from 1.0.x ? So if you are using a number of plugins you would have to wait now for all of them to be finally updated to 1.1.x even though they will not use any new functionality etc. ? Should we allow to use plugin 1.1.x with 1.0.x together or not ?
> 
> @obecny What `plugins` exactly are you talking about here? If they are e.g. http client or any other integration with some library or framework, then they are "users" and should only use API. And then during any given runtime you can mix and mach users of both 1.0.x and 1.1.x version of API as long as you configure SDK version 1.1.x.

sry I meant api

**Comment by iNikem** [comment]
Also, just in case, I will remind that there is [this existing document](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md#stable)
