### ISSUE TITLE
Clarifications on Periodic metric reader

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-specification#2140]
**What are you trying to achieve?**

Implementing the SDK spec in Python

**Additional context.**

Copying for reference [Periodic exporting metric reader](https://github.com/open-telemetry/opentelemetry-specification/blob/e2a4f057a56517cdc43026459e3d5a22be420147/specification/metrics/sdk.md#periodic-exporting-metricreader):

> This is an implementation of the MetricReader which collects metrics based on a user-configurable time interval, and passes the metrics to the configured Push Metric Exporter.

Since it is a `MetricReader` impl, it has a [`collect()`](https://github.com/open-telemetry/opentelemetry-specification/blob/e2a4f057a56517cdc43026459e3d5a22be420147/specification/metrics/sdk.md#collect) method. Reading between the lines, I think the intention is that periodic metric reader subclasses the pull based `MetricReader` and starts a background timer which calls `collect()` and passes the metrics to the exporter. However, `collect()` doesn't really need to be exposed at all here, and probably shouldn't be called by anything except the background timer as it can cause undesired behavior.

For example, if a periodic metric reader is configured with delta temporality and someone besides the timer calls `collect()`, the exporter will never see the delta values from that interval.

> Collect SHOULD provide a way to let the caller know whether it succeeded, failed or timed out.

What happens if collection failed? Should the reader communicate that failure with the exporter or just log a message?

**Comment by reyang** [comment]
Discussed during the Metrics SIG meeting, the lack of precise description was kind of intentional in order to give room for language implementations.

What we can do - add one concrete example so we can help the implementers.

**Comment by reyang** [comment]
Another feedback - the fact that `meterProvider.ForceFlush` calls `metricReader.Collect` and then (if the reader has underlying exporters) calls `metricExporter.ForceFlush` is hard to understand.

**Comment by jmacd** [comment]
@aabmass wrote:

> as it can cause undesired behavior.

Instead of trying to prevent collect() or forceFlush() on the periodic reader, can _something else_ be specified not to have the undesired behavior? I'm not sure anything needs to be specified: "exporters SHOULD avoid undesirable behavior"?

>  For example, if a periodic metric reader is configured with delta temporality and someone besides the timer calls collect(), the exporter will never see the delta values from that interval.

I think the purpose of `MetricReader` is to ensure that every `collect()` is passed to the exporter. I don't see your example as a valid / possible outcome. (How can we improve the spec to be clear about this?) 

> > Collect SHOULD provide a way to let the caller know whether it succeeded, failed or timed out.

> What happens if collection failed? Should the reader communicate that failure with the exporter or just log a message?

I think this is a good question, but it might be out of scope for the SDK spec and fall into general error-handling guidelines. I don't expect there are many reasons for collect() of the synchronous instruments to fail, so I expect the exporter will receive some data in the ordinary case. If asynchronous instrument collection causes trouble, which should be anticipated, then I would propose we develop semantic conventions for conveying this information to the receiver. I, personally, would avoid using logs for this purpose. (It will be too noisy. I would use self-diagnostic metrics based on semantic conventions we develop to convey the number of such failures.)

**Comment by aabmass** [comment]
> I think the purpose of `MetricReader` is to ensure that every `collect()` is passed to the exporter.

Ya, this is the thing I was missing before. For some reason I thought `collect()` should return a batch of metrics, not that it would pass on collected metrics to the configured exporter.

I am going to submit a PR with Reiley's suggestion of "add one concrete example so we can help the implementers."
