### ISSUE TITLE
Clarify how should SDK invokes async instrument callbacks

### ISSUE THREAD

**Issue by legendecas** [open-telemetry/opentelemetry-specification#2408]
**What are you trying to achieve?**

In the change of https://github.com/open-telemetry/opentelemetry-specification/pull/2361, it defines that:

> Callback functions MUST be documented as follows for the end user:
> - Callback functions SHOULD be reentrant safe. The SDK expects to evaluate callbacks for each MetricReader independently.

It sounds like the SDK can invoke the callback functions _each time_ a MetricReader initiates collection. While implementing the behavior, I found that when the async instrument is configured with multiple views with different names, a created async instrument may be mapped into multiple underlying, exported async instruments. The problems are:

1. Should the SDK call the callback _each time_ a MetricReader initiates collection, or one concurrent invocation for each MetricReader independently?

Like, we have two readers, should the SDK call the callback when reader A initiates a second-time collection when the first collection is not timed out yet?

2. Should the SDK call the callback once for an end-user registered async instrument, or for a view-ed async instrument?

**Comment by jmacd** [comment]
The specification is missing something from the recent revisions. #2317 should have added one more statement, more-or-less implied I think, in `sdk.md#observations-inside-asynchronous-callbacks` about executing callbacks exactly once per collection.

The pending PR #2363 includes the statement I had intended in an explicit way, since the option to support multiple callbacks requires more precision. See https://github.com/open-telemetry/opentelemetry-specification/pull/2363/files#diff-055661289c337a191d4767d311dbdf1fe63e0aa07f9d58944da92c54f4382df1R359. The specification there is intended to give an SDK of the future freedom to collect instruments with different intervals (i.e., "exactly once" applies to callbacks, but only to callbacks associated with desired instruments).

Please use the interpretation in that PR. Every callback is evaluated once during collection. If a value from an asynchronous instrument is used in multiple views, they should use identical values.
