### ISSUE TITLE
Extend semantic conventions for RPC

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#27]

**Comment by tedsuo** [comment]
Closing this as it is getting scooped up into the latest semantic convention work

**Comment by arminru** [comment]
@SergeyKanzhelev @tedsuo 
While this was partially addressed in #349, I do not think that semantic conventions for RPC are complete yet. It would make sense to add the RPC method and flavor/system, for example. Please reopen.

**Comment by jmacd** [comment]
I believe this was fixed by #349 and #386.

**Comment by Oberon00** [comment]
I think the last comment by @arminru still applies, we only have conventions for the very narrow special case of grpc. Please reopen again.

**Comment by arminru** [comment]
Yet to be done (as already mentioned above):
- allow RPC systems/frameworks other than gRPC
- add attribute for the RPC system/framework/flavor being used
- add the method name so that it doesn't have to be parsed out of the span name and to make it available for sampling decisions since the span name is not reliable to use (#506)
