### ISSUE TITLE
Do we still need `component` in semantic conventions?

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-specification#271]
For example, in specification/data-semantic-conventions.md for HTTP

> | `component`    | Denotes the type of the span and needs to be `"http"`. | Yes |

It's not clear what the value of this _required_ attribute is given that the HTTP-nature of the span can be inferred from the other required attributes like `http.method`, so it only bloats the data size. Also, the [OTEP 16](https://github.com/open-telemetry/oteps/blob/master/text/0016-named-tracers.md) provides another mechanism for identifying the type of library/component.

**Comment by Oberon00** [comment]
When going over the component attributes, it seems that the use of the component attribute is different for each convention:
* gRPC: Component must  be grpc, only way to detect gRPC, as the other attributes are the generic `peer.*`
* db: Component is vaguely defined, but no fixed string at least (see #245)
* http: Seems redundant, as other required `http.*` attributes exist.

So maybe it was put there just for consistency?

BTW, in OTEP 16 (named tracers), you specify the name of the instrument*ing* library, not the instrumented library, so that's not really the use case.

**Comment by bogdandrutu** [comment]
I think OTEP should use the name of the instrumented library not the name of the instrumentation.

**Comment by Oberon00** [comment]
@bogdandrutu I think you are wrong (or I am misunderstanding your sentence):

> The name used to create a Tracer or Meter must identify the instrumentation libraries (also referred to as integrations) and not the instrumented libraries. 

-- https://github.com/open-telemetry/oteps/blob/master/text/0016-named-tracers.md#explanation

**Comment by pauldraper** [comment]
> the HTTP-nature of the span can be inferred from the other required attributes like http.method

Much better to explicitly specify the component than try to guess based on other attributes. grpc is a good example, where it reuses the http attributes.

I would go a far as to say traces ought to always have component, as a quick way of seeing the instrumented technology.

**Comment by jmacd** [comment]
This needs discussion in the next Spec SIG meeting.

**Comment by bogdandrutu** [comment]
Discussed during the meeting to remove it.

**Comment by MatthewDolan** [comment]
> Discussed during the meeting to remove it.

Is there a link to the recording or notes from the meeting? I am curious what factors were weighed in the decision.
