### ISSUE TITLE
http.target in client traces

### ISSUE THREAD

**Issue by amoscatelli** [open-telemetry/opentelemetry-specification#2712]
**What are you trying to achieve?**

I would like http.target to be added in client traces by spec (maybe replacing http.url)

**Additional context.**

(https://github.com/open-telemetry/opentelemetry-js/issues/3147)

As already commented in the above issue I think http.target would be better than http.url .
Used in combination with deployment.environment can be used to fetch spans and span metrics in much cleaner way.

In general I am suggesting, at least, to send http.url splitted in http.host and http.target by the spec.

What do you think ?

**Comment by Oberon00** [comment]
This removal was fully intentional, it used to be there before the very recent https://github.com/open-telemetry/opentelemetry-specification/pull/2469

@lmolkova re-designed the HTTP semantic conventions with the goal to remove redundant ways of reporting the same information. I believe Node.js is the only technology where the primary interface to the HTTP client is first creating a connection with the host and then using only the target. So it does not seem worth it to make an exception that only makes it easier for Node.js, but makes processing the data more complicated for every backend.

> As already commented in the above issue I think http.target would be better than http.url

How so?

>  Used in combination with deployment.environment can be used to fetch spans and span metrics in much cleaner way.

Can you elaborate? deployment.environment does not seem at all related here.

**Comment by trask** [comment]
Closing out as stale. Please add requested info if you are still interested in this issue and it can be re-opened.
