### ISSUE TITLE
Implement JSON in two other languages to ensure we are satisfied.

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#2797]

**Comment by tigrannajaryan** [comment]
I believe we have an implementation in Go (in the Collector) and in JavaScript (@dyladan can you please confirm?).

**Comment by dyladan** [comment]
Yes and I believe JS is the only language implementation

**Comment by tigrannajaryan** [comment]
Do we feel the need to implement it in one more language? In the Collector we have Go implementation of the OTLP/JSON receiver and exporter.

**Comment by dyladan** [comment]
only if we feel it would be useful. it's important for JS due to constraints on the runtime and on package size. this may also be of interest to android/ios where distributing protobuf/grpc may be unwanted bloat on the package? Possibly also for c/cpp where it may see use in embedded systems or similar restricted environments.

**Comment by jack-berg** [comment]
In java we don't have an OTLP http/json protocol exporter, but we do have logging exporters which log in OTLP json format.  The protocol part is pretty much the same with http/protobuf and http/json, so it should really just be the encoding that we're trying to increase confidence in. And java does have artifacts which produce the json encoding.

**Comment by tigrannajaryan** [comment]
I am going to close, but if anyone thinks we do need more implementations please feel free to reopen.
