### ISSUE TITLE
Clarification needed on exporter/reader configuration

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-specification#2854]
This issue is intended to track an issue identified in the 2022-10-04 specification SIG.

Currently [the specification states](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/metrics/sdk.md#metricreader):

> To construct a `MetricReader` when setting up an SDK, the caller
> SHOULD provide at least the following:
> 
> * The `exporter` to use, which is a `MetricExporter` instance.
> * The default output `aggregation` (optional), a function of instrument kind.  If not configured, the [default aggregation](#default-aggregation) SHOULD be used.
> * The default output `temporality` (optional), a function of instrument kind.  If not configured, the Cumulative temporality SHOULD be used.

However, it also states:

> Metric Exporters always have an _associated_ MetricReader.  The `aggregation` and `temporality` properties used by the OpenTelemetry Metric SDK are determined when registering Metric Exporters through their associated MetricReader. 

It was pointed out in today's specification SIG meeting that the first statement about configuration of the SDK needs to be interpreted with the context of the second regarding the exporter. Meaning the optional default output aggregation and temporality configuration is only directly configured with a reader if it does not accept an exporter. This is not clear to all readers of the specification and it was suggested we update the language of the specification.

### Proposal

- Link in the first metric reader section the second metric exporter section
- Update the configuration language of the metric reader section to state the default output aggregation and temporality need to come from the exporter.

**Comment by MrAlias** [comment]
cc @jsuereth @jmacd @tsloughter

**Comment by MrAlias** [comment]
github actions assigned this to @bogdandrutu but @reyang had said in the SIG meeting he would take this on (with low priority).

**Comment by reyang** [comment]
Assigned to myself.

**Comment by jmacd** [comment]
Thank you @MrAlias! Your proposal sounds good to me.

**Comment by MrAlias** [comment]
This looks like it is a duplicate of #2746 

It seems like a longstanding issue.

**Comment by jmacd** [comment]
I am willing to help fix the specification to clarify that MetricReaders are responsible for configuration and that how the defaults are determined is an implementation detail. I wrote the sentence in question,

> Metric Exporters always have an associated MetricReader. The aggregation and temporality properties used by the OpenTelemetry Metric SDK are determined when registering Metric Exporters through their associated MetricReader.

I want to call attention to the word "associated". IMO it is meaningless to speak of an exporter without its corresponding reader. They are configured together, at once, they are effectively inseparable. The reason we have this problem in the specification is that every language has its own idioms -- we have a situation where the SDK calls the exporter and the exporter-or-the-reader calls the SDK. Because of this cycle, the setup is an implementation detail. It's OK with me if the reader delegates to the exporter, it's OK with me if the reader receives functional options to say the same thing, and it's OK with me if there's a factory involved in the setup. Note that we have not specified the `Register()` method that many SDKs are using to bind the reader--that's also an implementation detail.

If the group consensus is that metric exporters MUST be delegated to via a specified interface, then we should specify those interfaces. Java uses a TemporalitySelector and an AggregationSelector. However, I prefer to follow the library guidelines -- exporters should handle protocols, which means readers should handle configuration.

**Comment by MrAlias** [comment]
Closing in favor of https://github.com/open-telemetry/opentelemetry-specification/issues/2746. This indeed is a duplicate of that.
