### ISSUE TITLE
Provide clarity on how non-string attributes are supposed to be provided through OTEL_RESOURCE_ATTRIBUTES

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-specification#2857]
**What are you trying to achieve?**

I'm trying to set a resource attribute that [has type `[]string`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/cloud_provider/aws/logs.md). However it is not possible to do so through the `OTEL_RESOURCE_ATTRIBUTES` as it only supports [strings for values](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#specifying-resource-information-via-an-environment-variable). 

This is specially important for applications that rely on auto instrumentation in which is not possible to set the resource programmatically.  (e.g. using the otel java agent)

**What did you expect to see?**

A clear alternative or a clear note that non-string resource attributes must be set through another mechanism other than `OTEL_RESOURCE_ATTRIBUTES`.

**Comment by rbailey7210** [comment]
Let's discuss in the next Spec Sig call

**Comment by carlosalberto** [comment]
I have mixed feelings about this as there's the risk of ending up with an over engineered item for this env var. For what is worth I've been mostly users using this to set strings only. Let's talk next Tuesday about this.

**Comment by svrnm** [comment]
Since the semantic conventions also contain the types of attributes, wouldn't it be doable to do the mapping there? So if I have something like `OTEL_RESOURCE_ATTRIBUTES="process.parent_pid=1234"` the code reading from that environment variable takes care of the type mapping to `int`?

This solution of course does not provide a fix for `string[]`, and it also does not help for attributes outside of the semantic convention, but it would not require a complex language within that environment variable that allows to set the type of a value.

**Comment by reyang** [comment]
FYI https://github.com/open-telemetry/opentelemetry-specification/issues/2891#issuecomment-1289241503
