### ISSUE TITLE
Semantic Conventions: default to seconds for duration units

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-specification#2977]
Prometheus and OpenMetrics strongly recommend that the units for measuring durations should be `seconds`. However, the [semantic conventions here](https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/http-metrics/) are in `milliseconds`.

This creates a lot of confusion in users who are expecting durations to be seconds and requires an addition ` / 1e3` when doing math with metrics that come from traditional Prometheus sources. For example, today Kubernetes metrics are all in `_seconds` mainly because of the Prometheus conventions. This would be similar for other existing systems as well.

Given its all floats, I think we should try and revist the decision to use `milliseconds` and try to align with Prometheus.

**Comment by gouthamve** [comment]
cc @jmacd @jsuereth

**Comment by jack-berg** [comment]
The [default buckets](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation) for explicit bucket histogram are aligned to milliseconds for `http.server.duration`. We've previously discussed that changing them is a breaking change and not allowed. Therefore, changing from milliseconds to seconds for duration would render the default buckets useless.

**Comment by gouthamve** [comment]
Hrm, so while converting from OTLP to Prometheus, we can always convert to `_seconds` in the case of explicit bucket histograms. Its simply downscaling the buckets by `/1000`.

But this is not possible with exponential histograms. Can we make it `milliseconds` for exponential histograms?

**Comment by gouthamve** [comment]
This also causes inconsistencies when ingesting metrics from both Prometheus sources and OTel sources into a single db. Half the exponential histograms would be in seconds and the other half would be in milliseconds with no good way to reconcile/aggregate the two.

It is possible convert with explicit bucket histograms, hence initially I didn't mind the unit being milliseconds, but when I realised that its not possible with exponential histograms, I wanted to propose this change.

**Comment by dashpole** [comment]
If we introduced a way for instrumentation to override the default set of buckets (which could still be overridden by views), would that allow individual instrumentation libraries to switch to seconds?

**Comment by jack-berg** [comment]
> If we introduced a way for instrumentation to override the default set of buckets 

So you're imagining using what has been referred to as the "hint API" to perhaps have all `http.server.duration` instrumentation to report in seconds and specify alternative default buckets that are sensible for seconds?

**Comment by nerdondon** [comment]
I like the idea of allowing instrumentation to override buckets in a way that is more friendly to measurement in seconds but I want to interject with perspective from service mesh instrumentation.

Currently [Istio](https://istio.io/latest/docs/reference/config/metrics/#metrics), [Dapr](https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md#http-monitoring-metrics), and [linkerd](https://linkerd.io/2.12/reference/proxy-metrics/#protocol-level-metrics) report request duration in milliseconds. A change to seconds as the unit of measurement seems like it would not be conducive to allowing the auto-instrumenting functions of these projects to adopt the HTTP semantic convention.

**Comment by gouthamve** [comment]
> Currently [Istio](https://istio.io/latest/docs/reference/config/metrics/#metrics), [Dapr](https://github.com/dapr/dapr/blob/master/docs/development/dapr-metrics.md#http-monitoring-metrics), and [linkerd](https://linkerd.io/2.12/reference/proxy-metrics/#protocol-level-metrics) report request duration in milliseconds

I don't see it being a big problem. Its easy to convert from a `milliseconds` to seconds in the fixed bucket histograms that they export. And they have the unit specified as well everywhere which means we can convert it internally.

If we land on `seconds` as the unit for exponential histograms then when the projects implement it, they can choose seconds. Switching from fixed bucket to exponential histograms is considered a breaking change in most projects so they could make the change when they make the switch.

**Comment by reyang** [comment]
Two things to consider:
1. If we change milliseconds to seconds, we should update the default histogram buckets as pointed out by @jack-berg https://github.com/open-telemetry/opentelemetry-specification/issues/2977#issuecomment-1324117308
2. Certain backends might prefer integer (which might be related to history, faster processing - e.g. int is in general faster than float, better storage efficiency - e.g. delta encoding).

**Comment by jsuereth** [comment]
> @jack-berg The [default buckets](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation) for explicit bucket histogram are aligned to milliseconds for http.server.duration. We've previously discussed that changing them is a breaking change and not allowed. Therefore, changing from milliseconds to seconds for duration would render the default buckets useless.

We had a lot of discussion in the semantic convention stability and actually the current proposal is that bucket boundary changes are *not* considered a breaking change, for a variety of reasons.  I'm going to be submitting a PR shortly updating metric semconv stability definitiions in the stability specification, but this is a part of it.

The TL;DR; is that in practice histograms are interacted with using a "percentile(histogram, 0.9)" function in most backends, and this should remain stable across changes of buckets.  You're just shifting where the error accrues.

**Comment by pirgeo** [comment]
One other thing to consider here: Durations are almost never recorded in seconds, all programming languages that I can think of are either using millis or nanos, so by specifying seconds we would force everybody to perform this (albeit cheap) conversion. This conversion would then only benefit users that use a backend that prefers seconds.

**Comment by jack-berg** [comment]
[Here's](https://github.com/open-telemetry/opentelemetry-specification/pull/2770) previous discussion about whether changing default bucket boundaries is breaking. Based on the PR's phrasing "SDKs SHOULD use the default value when boundaries are not explicitly provided, unless they have good reasons to use something different (e.g. for backward compatibility reasons in a stable SDK release)", the conclusion is that even the less disruptive adding of buckets is probably a breaking change.

**Comment by jsuereth** [comment]
@jack-berg That logic is similar to claiming that changing label values is a breaking change, which we have not done yet.   I think we should take that portion of the discussion to a future PR, but I disagree this should be considered a breaking change.  I used to think this was a breaking change (e.g. during that PR), but in doing a lot of research into instrumentation stability requirements, I agree with @jmacd's comment.

E.g. OpenMetrics does NOT consider this breaking: https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#histogram

**Comment by jmacd** [comment]
@gouthamve wrote:

> But this is not possible with exponential histograms. Can we make it seconds for exponential histograms?

Yes, we should advise against scaling exponential histograms because it is a lossy operation. It is better to choose an ideal unit based on the range of measurement.

@jsuereth wrote:

> The TL;DR; is that in practice histograms are interacted with using a "percentile(histogram, 0.9)" function in most backends, and this should remain stable across changes of buckets. You're just shifting where the error accrues.

The choice of units gives users a slight way to improve exponential histogram performance, because the representation favors values near 1.0. If you are histogramming a request that takes around 1 second, the best choice for units is seconds. If you're histogramming a request that takes around 1 millisecond, the best choice is milliseconds. Example: measurements in (1.0, 2.0] seconds for a coarse histogram of 4 buckets, compared with measurements in (1000, 2000] milliseconds. In both cases, we expect scale=2 because there are 4 buckets for 1 order of magnitude. These structures have the same relative error.

In the first case (seconds), buckets will have offset 0 or 1 with boundaries at 1.0, 1.189, 1.414, 1.682, 2.0.

In the second case (milliseconds), buckets will have offset 39 with lower boundaries at 861, 1024, 1217, 1448, 1722, 2048.

This makes the seconds histogram slightly more compressible than the milliseconds histogram; we can also see how it is impossible to convert without loss between these histogram representations by scaling bucket boundaries.

**Comment by gouthamve** [comment]
I was just thinking about @reyang's point:

> Certain backends might prefer integer (which might be related to history, faster processing - e.g. int is in general faster than float, better storage efficiency - e.g. delta encoding)

I want to understand the storage reasoning, because the _values_ for each bucket is an integer anyways. In Prometheus, the `_bucket`, `_count` are integer values as they are all counts, and only `_sum` is a float. So only ~10% of the samples would be in floats with seconds compared to milliseconds. I would think the storage benefits are small.

Another thought: this is slightly tangential to HTTP, but we won't be able to measure less than millisecond durations if we use an integer.

**Comment by jsuereth** [comment]
@jmacd I think the proposal here is specific to HTTP semantic conventions.  The question there is if we expect HTTP services to be typically measured in milliseconds or seconds.

@gouthamve I do think the [points about exponential histogram here](https://github.com/open-telemetry/opentelemetry-specification/issues/2977#issuecomment-1331189527) are important to consider if we push for a convention.  I also think we need to fully align on the notion that Exponential histogram bucket boundaries (in OTEL) are designed so that they change to match the best resolution achievable in a limited amount of memory.  The goal (from OTEL) is not to require users (or instrumentation authors) to understand dynamic range of what's being measured.  From that perspective, the choice of unit entering into the instrument is important, particularly given the algorithm in use.

Personally, I'm still divided on this issue.  I see a lot of prometheus instrumentation and I'd be concerned if the friction between OTEL Semantic conventions *and* prometheus defaults would limit OTEL instrumentation adoption (i.e. if I'm already using PromClient for metrics, will this cause enough friction we won't see OTEL adopted for traces+metrics where otherwise it'd be compatible?)   I also understand the technical reasons why ms was chosen and see the friction it would cause in OTEL today to switch.

**Comment by jmacd** [comment]
@jsuereth based on your comments, I think we specify milliseconds as the conventional unit for HTTP durations. Prometheus uses this unit, and the Statsd Timing measurement uses milliseconds as well. I take it we would recommend floating-point instruments when there is an expectation of sub-millisecond measurements and recommend integer instruments when there is no such expectation. Either way, the exported histogram data points do not reflect the original integer-vs-floating-point distinction.

**Comment by gouthamve** [comment]
> based on your comments, I think we should leave the specification for milliseconds as the conventional unit for HTTP durations

I don't yet see it, but I might be mistaken. From what I understood, this is the algorithm to pick the scale: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exponential-bucket-histogram-aggregation (with the default of 160 buckets, for example).

If the typical requests are around 500ms-2000ms, then picking `seconds` as unit would mean more accuracy. If they are around 1-100ms, then picking `milliseconds` would be better. Or am I completely off-base here somehow?

> Prometheus uses this unit, and the Statsd Timing measurement uses milliseconds as well.

Prometheus uses `seconds` unfortunately :(

**Comment by dpk83** [comment]
For lot of services, request latencies for most of the requests is desired to be within few milliseconds to few hundred milliseconds so having seconds as the default unit of measurement doesn't look to be the right direction.

Also, as @reyang mentioned earlier in many systems performance is critical and integer is preferred for performance reasons 
as some backends can handle the storage and performance better with integer.

**Comment by dashpole** [comment]
We discussed this in the prometheus wg yesterday, and had one idea that might work for this case: Similar to how metric readers can be configured with an optional default aggregation temporality, metric readers should accept configuration for units.  Similar to how exporters are paired with the temporality they support, exporters can be paired with the units they support.

**Comment by bertysentry** [comment]
I'm surprised by this discussion. General semantic conventions recommend using standard base units. For example, for all metrics that measure size (disk, memory, payload, etc.), we recommend using bytes, even though GB or TB would be much more practical for a disk or a filesystem. Same should go for time.

All stacks now have separate storage and formatting methods. You store time values in seconds in your database, but then you display these values in whatever unit fits best. 

You guys mentioned earlier that milliseconds is best for HTTP response times. But one could argue that **centiseconds** is the best unit (10^-2 seconds). And in 5 years, we may all be discussing HTTP response times in microseconds! I mean: milliseconds is an arbitrary choice.

Note: Also I'm not sure to understand why the exponential histogram makes a difference. 

Note 2: I understand that changing the unit for HTTP response times is going to cause a lot of trouble...

**Comment by reyang** [comment]
> I'm surprised by this discussion. General semantic conventions recommend using standard base units. For example, for all metrics that measure size (disk, memory, payload, etc.), we recommend using bytes, even though GB or TB would be much more practical for a disk or a filesystem. Same should go for time.
> 
> All stacks now have separate storage and formatting methods. You store time values in seconds in your database, but then you display these values in whatever unit fits best.
> 
> You guys mentioned earlier that milliseconds is best for HTTP response times. But one could argue that **centiseconds** is the best unit (10^-2 seconds). And in 5 years, we may all be discussing HTTP response times in microseconds! I mean: milliseconds is an arbitrary choice.

+1 👍

> Note: Also I'm not sure to understand why the exponential histogram makes a difference.

The current "base-2 buckets exponential histogram" has different resolution depending on the range of the numbers. Taking an extreme case, if we have a super large unit and all the durations become very tiny numbers, they tend to end up "squeezed" into the same bucket which makes the histogram less useful.

> Note 2: I understand that changing the unit for HTTP response times is going to cause a lot of trouble...

Also it is counterintuitive (I know this is very subjective), most likely people are going to see something like "0.0001" (and I guess that's why we have different units, I don't know that's a problem we can/should solve in OpenTelemetry).

**Comment by reyang** [comment]
> We discussed this in the prometheus wg yesterday, and had one idea that might work for this case: Similar to how metric readers can be configured with an optional default aggregation temporality, metric readers should accept configuration for units. Similar to how exporters are paired with the temporality they support, exporters can be paired with the units they support.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md

"It SHOULD be treated as an opaque string from the API and SDK (e.g. the SDK is not expected to validate the unit of measurement, or perform the unit conversion)."

**Comment by bertysentry** [comment]
> > Note: Also I'm not sure to understand why the exponential histogram makes a difference.
> 
> The current "base-2 buckets exponential histogram" has different resolution depending on the range of the numbers. Taking an extreme case, if we have a super large unit and all the durations become very tiny numbers, they tend to end up "squeezed" into the same bucket which makes the histogram less useful.

See, I think we're all wrong here. According to [the OpenTelemetry SDK for exponential histograms](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exponential-bucket-histogram-aggregation), the precision of the buckets doesn't depend on the raw values, but on the scale (or contrast) between the values, i.e. the ratio between the smallest and the largest value.

If we take this table from the SDK:

> | Input range | Contrast | Ideal Scale | Base | Relative error |
> |---|---|---|---|---|
> | 1ms - 1000ms | 10**3 | 4 | 1.04427 | 2.166% |

We can convert this example to seconds and get the same precision and relative error:

> | Input range | Contrast | Ideal Scale | Base | Relative error |
> |---|---|---|---|---|
> | 0.001s - 1s | 10**3 | 4 | 1.04427 | 2.166% |

So the unit **DOES NOT** have any effect on the precision of the buckets in an exponential histogram.

So we can safely use seconds for HTTP response times... if we decide to!

**Comment by reyang** [comment]
> > > Note: Also I'm not sure to understand why the exponential histogram makes a difference.
> > 
> > 
> > The current "base-2 buckets exponential histogram" has different resolution depending on the range of the numbers. Taking an extreme case, if we have a super large unit and all the durations become very tiny numbers, they tend to end up "squeezed" into the same bucket which makes the histogram less useful.
> 
> See, I think we're all wrong here. According to [the OpenTelemetry SDK for exponential histograms](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exponential-bucket-histogram-aggregation), the precision of the buckets doesn't depend on the raw values, but on the scale (or contrast) between the values, i.e. the ratio between the smallest and the largest value.
> 
> If we take this table from the SDK:
> 
> > Input range
> > Contrast
> > Ideal Scale
> > Base
> > Relative error
> > 
> > 
> > 
> > 
> > 1ms - 1000ms
> > 10**3
> > 4
> > 1.04427
> > 2.166%
> 
> We can convert this example to seconds and get the same precision and relative error:
> 
> > Input range
> > Contrast
> > Ideal Scale
> > Base
> > Relative error
> > 
> > 
> > 
> > 
> > 0.001s - 1s
> > 10**3
> > 4
> > 1.04427
> > 2.166%
> 
> So the unit **DOES NOT** have any effect on the precision of the buckets in an exponential histogram.
> 
> So we can safely use seconds for HTTP response times... if we decide to!

Hmm, I think if you take rounding, boundary and other implementation details into account, things will be different.

**Comment by bertysentry** [comment]
> Hmm, I think if you take rounding, boundary and other implementation details into account, things will be different.

With floating-point numbers, rounding and boundaries are not supposed to be a problem either (of course, it's a different story with integers). On a typical computer system, a [double-precision](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) (64-bit) binary floating-point number has a coefficient of 53 bits (including 1 implied bit), an exponent of 11 bits, and 1 sign bit. Since 2\*\*10 = 1024, the complete range of the positive normal floating-point numbers in this format is from 2\*\*−1022 ≈ 2 × 10\*\*−308 to approximately 2\*\*1024 ≈ 2 × 10\*\*308.

Really I would like everybody here to understand that the unit choice is never going to be a problem when it comes to exponential histograms, or any metric type.

We must only take into consideration what "is right" (IMO: always use the base units, as most modern systems do, do avoid painful conversion discussions later 😉).

**Comment by ahayworth** [comment]
I wanted to chime in (again) with the specific feedback that while changing the units may be a good idea, we really need to consider it on its own merits. There is a fine line between shaping a standard based on what current systems can/should support, and setting your shaping a standard based on what we want to be in the future.

We should err on the side of considering this change on its own merits, regardless of what Prometheus does or does not support. It's a valuable data point to consider, but we are setting standards for systems that include more than just Prometheus today - and if we're good at it, will include more than just Prometheus tomorrow. Prometheus is _not_ the defacto standard across all metrics systems that might be adopting OpenTelemetry: that's a particular blind spot that we sometimes have in CNCF projects. Prometheus support is not the only concern that exists - and it's worth noting that the standards we set here can influence Prometheus as well (hopefully, for the better).

**Comment by dpk83** [comment]
I want to echo what ahayworth said. We have thousands of services in our org which don't use Prometheus and using milliseconds for the request duration is so ingrained that it is going to be extremely difficult (nearly impossible) to get services to onboard to OpenTelemetry auto instrumentation if it decides to go with seconds.

I understand the point that choosing milliseconds on the other side is going to have the same impact on the current consumer of Prometheus.

It will be great to give it more thought or atleast provide a flexibility for users to choose the unit.

**Comment by bertysentry** [comment]
@dpk83 Well, if it's impossible for your org to use seconds, you always have the possibility not to follow the semantic convention (it's just a convention, after all). However, this is not what we recommend!

@ahayworth Totally agree with your point. Considering the change on its own merits in this case would mean that we shouldn't keep milliseconds just because it was set this way at the beginning of the specification. Considering the future, we want to normalize the units with base units (it's not as if we were using integers to store HTTP request durations).

**Comment by dpk83** [comment]
@bertysentry It's not just about semantic conventions, it's the fact that in that case we won't be using the auto instrumentation provided by OpenTelemetry and will have to write our own. And if we keep doing this for all such auto instrumentation than I have to question the value that OpenTelemetry brings in the first place as we have to rewrite a bunch of the things that exists in OpenTelemetry but it doesn't provide us the flexibility to serve the need.

**Comment by reyang** [comment]
> @bertysentry It's not just about semantic conventions, it's the fact that in that case we won't be using the auto instrumentation provided by OpenTelemetry and will have to write our own.

Why is that the case? Some translation can happen at the later stage of the collection (e.g. process, exporter, collector, query backend), which is much cheaper than making all the instrumentation libraries from scratch.

**Comment by dpk83** [comment]
> > @bertysentry It's not just about semantic conventions, it's the fact that in that case we won't be using the auto instrumentation provided by OpenTelemetry and will have to write our own.
> 
> Why is that the case? Some translation can happen at the later stage of the collection (e.g. process, exporter, collector, query backend), which is much cheaper than making all the instrumentation libraries from scratch.

It's doable but that's additional perf cost for fetching and updating the values

**Comment by reyang** [comment]
> It's doable but that's additional perf cost for fetching and updating the values

Which should be very low cost considering that metrics are already pre-aggregated. And it is much lower than "will have to write our own"?

**Comment by dpk83** [comment]
> Which should be very low cost considering that metrics are already pre-aggregated. And it is much lower than "will have to write our own"?

It depends on how you look at this. It's the question of one time cost of writing the library vs runtime cost for every request and not to mention all these little things add up.

**Comment by trask** [comment]
I'm concerned about the disconnect between the default buckets being aligned to milliseconds and the default duration being seconds.

I think the OpenTelemetry "default" buckets should match the OpenTelemetry "default" duration unit.

While it's true that this "default" duration unit only applies to semantic conventions, I think it will be more broadly seen as the "default" duration unit for OpenTelemetry, which will then create confusion for users who are emitting their own timing metrics.

**Comment by jsuereth** [comment]
From the specification meeting, a suggestion:

- We can provide *different* default histogram bucket boundaries by the unit string provided in the instrument.
- The current default can be a fallback for unknown/unspecified unit in the new default.
- This aligns with #3184 where views can now provide different buckets/aggregations by unit.

So for example, the bare minimum specification could be:

- Default bucket boundaries when unit is `s` are `[0, 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10 ]`
- Otherwise, default bucket boundaries are `[ 0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000 ]`

**Comment by reyang** [comment]
> We've discussed this during the [Feb. 14th specification SIG meeting](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit#heading=h.nboyren5yfyz):
> 
> 1. We will make the change to use seconds instead of ms, which aligns with Prometheus.
> 2. The change might introduce some issue to existing specification, for example [Semantic Conventions: default to seconds for duration units #2977 (comment)](https://github.com/open-telemetry/opentelemetry-specification/issues/2977#issuecomment-1324117308). We believe this issue can be resolved via Hint API, and @jack-berg is willing to propose a small addition to the spec (minimal Hint API for explicit histogram buckets).
> 
> Based on the discussion, I've changed the status to `triage-accepted`. Assigning to @trask.

^ this was the consensus from the spec meeting, if anyone disagrees and would like to request the TC (technical committee) to make the final call, please reply here explicitly before end of Mar. 7th (Pacific Time).

@trask FYI

**Comment by pirgeo** [comment]
I am going to summarize my understanding of this issue. I don't have a dog in this fight, I just want to make sure we make such wide-reaching changes for the right reasons. 
Here are a few considerations. All of them have been mentioned in the thread above. I will try to condense them into a short summary:

**In favor of changing:**
* It is compatible with Prometheus without having to do any conversions.
	* With this change, users do not have to explicitly set up their exponential histograms to be Prometheus compatible. If this change is *not made*, it would still be possible for users to set up their exponential histograms to use seconds, but it wouldn’t just magically all work out of the box.
* It is aligned to SI units.

**In favor of not changing:**
* The OpenTelemetry community has introduced the Histogram with a set of default boundaries. These boundaries work well when measuring latency because we believe that this is the primary use case. Today, latencies are mostly measured in milliseconds, because that is the order of magnitude that makes the most sense. The bucket boundaries would therefore be aligned to the primary use case, while the unit would not.
* Using seconds feels counterintuitive when working with latencies, especially if someone just wants to use OTel but not understand this whole thread.
* Numbers below 0.25 (`0, 0.005, 0.01, 0.025, 0.05, 0.075, 0.1`) that are mentioned in the default bucket boundaries above cannot be accurately represented in double precision. This might lead to rounding errors and bucket assignments that are different between producer and consumer, depending on the implementation of the floating point number.
* There are many other data sources that are not Prometheus that use milliseconds. Instead of breaking the Prometheus users, this change has the potential to break everyone _but_ the Prometheus users.
* Automagically changing the default boundaries based on the unit is a magic conversion that might surprise a lot of users.

It seems we have established that it is technically possible to change the defaults. I am wondering if I am missing the point in this discussion about why we absolutely need to go to seconds when the main target of what we are trying to do with this aggregation (namely measuring latencies) is in milliseconds. With the Hints API on the horizon, would that not allow everything to work without having to change such a fundamental concept and breaking existing implementations along the way?

**Comment by bertysentry** [comment]
@pirgeo Thank you for the recap'! I need to comment on a couple points you made:

1. Numbers in double precision can go to 10^-308 in precision (all double implementations in languages supported by OpenTelemetry follow the standard definition for [double-precision](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) (64-bit) binary floating-point numbers). So numbers below 0.25 are never going to be a problem, there will be no rounding errors.
2. Milliseconds are not that common when talking about latencies. HTTP responses are often in this range, but application transactions, payments, OAuth authentication, etc. are often in the 1-10 seconds range. On the other end, ping response time on a LAN will often go below 1 milliseconds and may be better expressed in microseconds. A Java method execution time will be better expressed in nanoseconds. My point is: Milliseconds are not better, than microseconds, or seconds. It depends on the context. Histogram default buckets don't apply just for HTTP response times.

Your other points stand though!

**Comment by pirgeo** [comment]
@bertysentry, yes, but not all numbers in that range can be excatly represented. If you store `0.1` as a `double`, for example, you will actually store `0 01111111011 1001100110011001100110011001100110011001100110011010` in binary (spaces show sign bit, exponent and mantissa boundaries). If you do the math of converting from that binary representation to decimal again, you will end up with `0.1000000000000000055511151231257827021181583404541015625`, which is very close, but not exactly the same. The number `0.25` can be exactly represented in binary as `0 01111111101 0000000000000000000000000000000000000000000000000000`, which in turn yields _exactly_ 0.25 again (because it can be exactly represented in binary).

This should not be the main driver for this conversation anyway, but I thought it was interesting enough to mention it, especially if we decide to use such numbers as a default.

Ad 2: You are right, there are many things that you can measure in histograms that do not align well to these boundaries. But: My understanding is, that the default boundaries are intended for the default use case, which is measuring HTTP latencies. At least my feeling is that this is one of the use-cases that most users will benefit from/will expect to see from OTel. Another use-case that is pretty prominent in the semantic conventions is measuring something in Bytes (e.g. a Response size). The use of `[ 0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000 ]` for response sizes is questionable, but `[0, 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 2.5, 5, 7.5, 10 ]` seems really off. For anything else (and probably even for response sizes) you will want to use different bucket boundaries anyway. 

I understand that the arguments I am making here are purely technical, and that it would make sense for the semantic conventions to use SI base units.  but these semantic conventions have grown organically based on what people needed at the time. The things that are codified in the OTel semantic conventions today are already used widely, and they seem to work for many folks.

**Comment by bertysentry** [comment]
We have a problem: many metrics in our semantic conventions use milliseconds, and don't follow the same naming rules (`usage` vs `time` vs `duration`):

* `faas.invoke_duration`
* `faas.init_duration`
* `faas.cpu_usage`
* `db.client.connections.create_time`
* `db.client.connections.wait_time`
* `db.client.connections.use_time`
* `http.server.duration`
* `http.client.duration`
* `rpc.server.duration`
* `rpc.client.duration`
* `process.runtime.jvm.gc.duration`

Even though it's "the right thing to do", it's going to be difficult to change all these metrics to seconds.

Maybe another suggestion:

1. Keep `*.duration` histogram metrics in milliseconds ==> backward compatibility
2. Introduce **new** `*.time` metrics, expressed in seconds (to follow `system.cpu.time`, `process.cpu.time`, etc. which are expressed in seconds) ==> future standard
    * `http.server.request.time` (equals `http.server.duration`, but expressed in seconds)
    * `http.client.response.time` (equals `http.client.duration`, but expressed in seconds)
    * `rpc.server.request.time` (equals `rpc.server.duration`, but expressed in seconds)
    * `rpc.client.response.time` (equals `rpc.client.duration`, but expressed in seconds)
    * `process.runtime.jvm.gc.time`
    * `faas.invoke.time`
    * `faas.init.time`
    * `faas.cpu_time`
    * `db.client.connection.create.time`
    * `db.client.connection.wait.time`
    * `db.client.connection.use.time`
3. Solve the conflict we have with `db.client.connections.*time`:
    * Rename `db.client.connections.create_time` to `db.client.connection.create.duration`
    * Rename `db.client.connections.wait_time` to `db.client.connection.wait.duration`
    * Rename `db.client.connections.use_time` to `db.client.connection.use.duration`
4. Deprecate (maybe, someday, if usage shows people adopted the new time metrics) `*.duration` metrics

**Comment by bertysentry** [comment]
@pirgeo Ha ha, thank you for the details on double-precision numbers, but you'll notice that 5, 50, 75, 500, 750, 2500, 5000, 7500 and 10000 can**NOT** be represented exactly with a double-precision either (5 will actually be 5.00000000000000088817841970012523233890533447265625, for example), so it's definitely not a concern for this discussion😉

**Comment by pirgeo** [comment]
Maybe I am missing something here but if I understand the IEEE 754 correctly, then 5 would be represented as `0 10000000001 0100000000000000000000000000000000000000000000000000` in binary, which can again be represented exactly.

**Comment by bertysentry** [comment]
@pirgeo You're totally right! I got my double-precision really wrong 😅

**Comment by pirgeo** [comment]
Yes, I agree. I think there is no right or wrong here, both milliseconds and seconds are used and will break some users, regardless of what we do.

I think the point that I am trying to make is that the OpenTelemetry community built these semantic conventions with a rather specific use case in mind, for which milliseconds usually work well. Instrumentations that already implemented these semantic conventions will no longer be compliant. That's okay, the semantic conventions are experimental right now. Users that get their data from other data sources that use milliseconds, and that align well with the OTel SemConv now will have to find ways of transforming their data to stay compliant or move away from the SemConvs. I think the problem we are facing here is that the milliseconds are already rather ingrained into the OTel world, and it will be hard to move all of that now. Maybe I am just wrong about that though, and it will be a breeze anyway. On the other hand, keeping them in milliseconds requires users that use a Prometheus backend to convert their new metrics if they want it to align with the other metrics that they have in seconds.

However, what worries me most is that we make such a sweeping change relatively late. With the push for HTTP semantic conventions stability, we will want to mark them as stable as soon as possible. Completely changing the metric shortly before stabilization seems... potentially disruptive. We will end up with a hodgepodge of instrumentations that do different things. That is probably also okay. It should work itself out over time, although I assume many people have a lot of work ahead of them to align this in their instrumentations, applications, and the data views in their backends. (I wonder if that will harm adoption.)

Either way, I understand the needs of both sides. But: can we introduce such a change so abruptly? I know I have been playing the devil’s advocate on this issue, but I really want us to do things right. I think this issue is also to a certain degree a question of how we deal with incompatibilities between the Prometheus and OpenTelemetry projects in the future. We have been trying to maintain compatibility in most areas but there will be differences here and there, especially as we mark more and more parts of the spec as stable. Do we go for compatibility at all costs? The answer might very well be yes, and that is okay, too! I think this is something for the OTel leadership to decide, and either way will work for some, and not work for others.

**Comment by bertysentry** [comment]
@pirgeo What do you think of my suggestion? (separate metrics for milliseconds (`*.duration`) and seconds (`*.time`)

**Comment by pirgeo** [comment]
@bertysentry In theory I think it's a good idea if we want to do a transition period, but it would duplicate a lot of the semantic conventions that we have today. It would probably lead to a similar state where every instrumentation is using the one that fits them, and we are just punting the problem. It's a possible solution, but I think we'd rather keep the semantic conventions we have today, and agree on one default.

**Comment by yurishkuro** [comment]
My 2c - this could be handled via stronger typing making the question of units a non-issue. Many languages today have established conventions for default time units, e.g., in Python it's seconds, in Go/Java the units are provided explicitly. Since capturing durations is one of the primary functions of OTEL, our APIs could have dedicated methods for that, where units are either explicit or follow language convention. This makes the instrumentation immune to changes being discussed in this issue.

Then we have transmission and exposition formats. In OTLP we can include units, or even specialize durations as a value type. In other exposition formats the exporter follows the existing format's conventions.

**Comment by reyang** [comment]
> > We've discussed this during the [Feb. 14th specification SIG meeting](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit#heading=h.nboyren5yfyz):
> > 
> > 1. We will make the change to use seconds instead of ms, which aligns with Prometheus.
> 
> ^ this was the consensus from the spec meeting, if anyone disagrees and would like to request the TC (technical committee) to make the final call, please reply here explicitly before end of Mar. 7th (Pacific Time).
> 
> @trask FYI

The TC (technical committee) has done the voting and 5 out 9 members voted for `seconds` as the recommended unit for duration.

In addition, we understand that semantic convention changes should be done in a careful way to reduce the negative impact. Several things should be considered:
1. Give the users a reasonable noticing period before the actual implementation change.
2. Explore ways to make it smoother (e.g. hint/advice API, translation).
