### ISSUE TITLE
how to call auto-collection modules

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#30]
Modules that can automatically collect telemetry from various technologies needs a common name consistent across the projects. How to name it:

Plugins? Instrumentation? AutoCollector? Other?

**Comment by fbogsany** [comment]
We called this "Adapter" in Shopify's tracing implementation. I'm not wedded to the name - just another option. It doesn't really describe the automatic part of auto-instrumentation. Neither does "Plugin" or "Instrumentation".

"Collector" seems overloaded, given the opentelemetry-service.

Is there a need to distinguish auto-instrumentation modules from manual instrumentation modules? Maybe some examples of the two approaches would be useful.

**Comment by SergeyKanzhelev** [comment]
I like Adapter. The hope is that at some point those wouldn't be needed as libraries will be instrumented with OpenTelemetry directly. So meanwhile we need an adapter.

Example may be SpringBoot adapter or ASP.NET Core adapter to collect information about incoming requests.

**Comment by austinlparker** [comment]
Adapter strikes me as hitting the balance we're looking for.

**Comment by tedsuo** [comment]
Discussing on a call today with @SergeyKanzhelev: o the OpenTracing side, we usually just refer to these components as "instrumentation." As to whether that instrumentation is a plugin, a wrapper, an interceptor, or an adaptor, that usually depends on how the target library or framework actually works. Different frameworks have different names for their extensibility mechanisms. It could be native instrumentation as well, once adoption picks up.

But, since we need to pick something for the spec, here's what I propose:

For referring to the concept itself in the spec, I suggest "instrumentation adapters." 

**Namespaces:** For languages where packages sit in a namespace, the namespace for instrumentation adapters should match "opentelemetry/instrumentation/TARGET_LIBRARY" as closely as possible.

How does that sound?

**Comment by austinlparker** [comment]
I think just 'adapter' makes more sense, especially where there's an existing telemetry or tracing functions that we would be adapting to OTel (java, .net, etc.)
