### ISSUE TITLE
Proofread Logs Bridge API and SDK in preparation to mark it Stable

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#3268]
We are preparing to mark Logs Bridge [API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md)/[SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md) Stable. Before we do that we need to proofread it, ideally by more than one person.

Anyone who is willing to work on this is welcome to become an assignee of this issue and file corrections/PRs.

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-logs-approvers FYI.

**Comment by martinkuba** [comment]
I spent some time going over the API and SDK spec, and it is not clear to me exactly how the implicit context injection should work. Since the `include_trace_context` config is for the Logger, I would assume that it would be the Logger's responsibility to add the span context fields on every LogRecord it emits. But there is also the Context parameter in the [OnEmit method of the LogRecordProcessor](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md#onemit), which does mention the `include_trace_context` option.

Questions
- Is it intended that the span context fields are set in the Logger itself or some processor?
- If it is the logger, what is the intent of passing the Context to the processor, and why does it rely on the `include_trace_context` config?

Also, there is a pending TODO in the [Implicit Context Injection section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#implicit-context-injection).

**Comment by martinkuba** [comment]
The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#emit-logrecord) says that the Logger method for emitting log records may be named `logRecord`. Is this the recommended/preferable name over `emit()`?

**Comment by jack-berg** [comment]
> Is it intended that the span context fields are set in the Logger itself or some processor?

No. Span context should either be set by the Logger (implicit context injection when `include_trace_context=true`), or explicitly by the caller if implicit context injection is not available of if `include_trace_context=false`. 

> If it is the logger, what is the intent of passing the Context to the processor, and why does it rely on the include_trace_context config?

The [context](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/README.md) that is available to processors may contain more than just trace context, for example baggage or any other entries in context. 

> Also, there is a pending TODO in the [Implicit Context Injection section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#implicit-context-injection).

IMO opinion that TODO is acceptable because its in the "usage" section and doesn't contain normative language.

**Comment by martinkuba** [comment]
@jack-berg Thanks for the clarification. Since the Context parameter for the processors is for more than the trace context, why does the spec say that it should be empty when `include_trace_context=false`?

**Comment by jack-berg** [comment]
Right so you're referring to the `context` argument of [LogRecordProcessor#onEmit](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md#onemit), which says:

> the Context that the SDK determined (the explicitly passed Context, the current Context, or an empty Context if the [Logger](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#get-a-logger) was obtained with include_trace_context=false)

It is a bit strange that `include_trace_context` has side effects wider than just the trace context which is included on the log record. Maybe we should change the language to drop say:

> the Context that the SDK determined (the explicitly passed Context or the current Context)

@open-telemetry/specs-logs-approvers WDYT?

**Comment by jack-berg** [comment]
#3354 also contributed to this.
