### ISSUE TITLE
Code generation fails for SEMCONV 1.19.0

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-specification#3299]
Using the latest spec 1.19.0 release.

Using build tools 0.17.0

Code generation for semantic conventions misses items in the generated code, leading to build breaks compared to version 1.18.0.

In particular, attributes like `http.method` got moved to common attributes by:

* https://github.com/open-telemetry/opentelemetry-specification/pull/3183

However, the code generation tool is not ready for this:

* https://github.com/open-telemetry/build-tools/issues/133

As a result, code generated with spec 1.19.0 + build tool 0.17.0 contains less constant definitions compared to 1.18.0, breaking the build because constants for `http.method` are missing:

* https://github.com/open-telemetry/opentelemetry-cpp/pull/2017

This is not only blocking for 1.19.0, but will also affect every semantic convention changes done from now on, until the build tools are fixed so that code can be generated again from yaml files.

**Comment by lmolkova** [comment]
I'm not sure if  build-tools#133 is related to the issue, but I'm looking into build-tools fix for code generation.

**Comment by lmolkova** [comment]
The problem is in https://github.com/open-telemetry/opentelemetry-specification/pull/3188 and https://github.com/open-telemetry/opentelemetry-specification/pull/3190 which reuse resource attributes in trace semconv.

Without these two, java templates work just fine. With them they show a bunch of errors. 

I believe Java templates work a bit better because they allow taking attributes from everywhere except resources ([`--exclude resource/**`](https://github.com/open-telemetry/opentelemetry-java/blob/main/buildscripts/semantic-convention/generate.sh#L29))  and cpp does this: [` --only span` ](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/buildscripts/semantic-convention/generate.sh#L49)

I created this issue https://github.com/open-telemetry/build-tools/issues/155 and should be able to work on it in a few days.

**Comment by lmolkova** [comment]
@tsloughter, @marcalff, and everyone else affected, would you mind trying new build-tools version - 0.18.0- with the fix? (thanks for @Oberon00  and @arminru for the help!)

It will be necessary to change the generation script to specify which signals to generate using `--only` flag. It's also important to point source to the root folder so that referenced attributes are resolved everywhere

Here's the sample of changes in Java 

Java generates all semconv except resources into one file
```diff
docker run --rm \
  -v ${SCRIPT_DIR}/opentelemetry-specification/semantic_conventions:/source \
  -v ${SCRIPT_DIR}/templates:/templates \
  -v ${ROOT_DIR}/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/:/output \
  otel/semconvgen:$GENERATOR_VERSION \
-  --exclude resource/** \
+  --only span,event,attribute_group,scope \
  -f /source code \
 ...
```

Resources:

```diff
docker run --rm \
- -v ${SCRIPT_DIR}/opentelemetry-specification/semantic_conventions/resource/:/source \
+ -v ${SCRIPT_DIR}/opentelemetry-specification/semantic_conventions:/source \
  -v ${SCRIPT_DIR}/templates:/templates \
  -v ${ROOT_DIR}/semconv/src/main/java/io/opentelemetry/semconv/resource/attributes/:/output \
  semconvgen:$GENERATOR_VERSION \
+ --only resource \
  -f /source code \
....
```

**Comment by tsloughter** [comment]
Hm, I'm getting `gen-semconv: error: unrecognized arguments: --only resource` with `0.18.0`

**Comment by tsloughter** [comment]
Hm, it works if its the first argument.

**Comment by Oberon00** [comment]
Yes, this is a bit of a quirk of Python's argparse: `--only` is an argument to the program itself, not to the `code` (or `markdown`) subcommand, so you need to specify it before the subcommand (similar to how you need to specify the `-v` to docker before the image name).

**Comment by marcalff** [comment]
> @tsloughter, @marcalff, and everyone else affected, would you mind trying new build-tools version - 0.18.0- with the fix? (thanks for @Oberon00 and @arminru for the help!)

Thanks for the fix.

It works, see C++ PR:

* https://github.com/open-telemetry/opentelemetry-cpp/pull/2017

**Comment by marcalff** [comment]
Before closing this issue for opentelemetry-specification, please consider to add a CI check, to enforce that semantic conventions always build after a spec semconv change in yaml files.

Credits for the idea to @lmolkova , see https://github.com/open-telemetry/build-tools/pull/156#issuecomment-1462404842

**Comment by marcalff** [comment]
There is no longer a point in implementing a CI check in the specification repository,
as semantic conventions moved to their own repo.

Closing this issue.

**Comment by Oberon00** [comment]
I can reopen & move it to the semconv repo instead if you prefer
