### ISSUE TITLE
Proposal: Add filter predicate to MetricReader (push-down predicate)

### ISSUE THREAD

**Issue by asafm** [open-telemetry/opentelemetry-specification#3324]
**What are you trying to achieve?**
I would like as a user to define a predicate (programmatically at first) to `MetricReader` which will allow me to read only a portion of metrics available in the SDK metrics producer or any other `MetricProducer`.

This will be marked as experimental in the spec.

**What did you expect to see?**

A new operation in `MetricReader`: `setPredicate(predicate)`

Where `predicate` will be a function matching the following interface:
`(instrumentationScope, instrumentName, instrumentDescription, instrumentKind, attributes, unit) -> boolean` 
The metric reader will provide that function to any registered `MetricProducer` upon calling `collect()`. Each producer will use that function to determine whether to produce a metric for given attributes in an instrument. A True value means the data point will be included in the result of the metrics producer, and there by respected by what ever the reader does with the data point.

A new optional parameter to `Produce()` operation of `MetricProducer`: 
`producer(predicate)`, where `predicate` is defined as above.

**Additional context.**

I'm working on [designing](https://github.com/apache/pulsar/issues/20197) the integration of OpenTelemetry Metrics into [Apache Pulsar](https://pulsar.apache.org/).
Pulsar supports today up-to 100k of topics (partitions in Kafka terms) in a single broker, and in the near future 1M topics per broker (possible since Pulsar persists the message into a virtual append-only files to Apache Bookkeeper, as opposed to actual file descriptors on disk).

In a single broker having 100k topics, with 50 instruments for topics, this means, 5000k attribute sets overall. As you can imagine, it is too much, response body size and cost wise. Hence, there are two ways I planned to solve it, where the 2nd way is the reason for this proposal:
1. Introduce new instruments, aggregating topic metrics to new level called Metric Topic Groups (grouping topics) which should have reasonable cardinality.
2. Given most will use the Metric Groups instruments, I would like to have the ability to filter by default all topic-level instruments. When is alerted something is wrong with a given topic group, they will want to dynamically "turn on" topic-level instruments for the topics in that group. 
This can be achieved with decorating the registered `MetricProducer` and filtering the result list, but this means we pay the cost of memory and CPU associated with collecting those amount of attributes (that can be quite a lot, as shows). In latency sensitive applications such as Apache Pulsar, every millisecond in latency counts.
Hence, I wanted to be able to provide a filter function which the SDK metric producer will use to determine which (instrument, attribute) pairs to collect or skip, whether synchronous or asynchronous (the callback `record()` method will do nothing).

I believe this is useful also for other purposes. Imagine the applications wish to expose some instruments and attributes via REST API in certain format. It can create a metric reader and set the filter, to obtain those values. The alternative is to record the values manually in memory and expose it via asynchronous instruments (which is not possible for histograms).
This REST API can also be a nice UI showing current metrics of the system.

Also, Prometheus `/metrics` endpoint today supports this kind of dynamic filtering via query parameters (`name[]`). This proposal will make it more efficient and more accurate (delta temporality resets count upon collect, but data got discarded forward in the pipeline).

**Comment by pirgeo** [comment]
Does this lead to the same output as basically turning off all the `(instrument, attribute_set)` tuples that are not desirable? Maybe I am missing the point here, I have never worked with Pulsar, but why record them in the first place if you intend to disable them later?

**Comment by asafm** [comment]
Turning off --> delete?
Think of it as DEBUG log-level. You record logs that in most cases you don't need, right? But in some cases you need to turn on DEBUG level to better understand what goes on, and then you turn it off.

Apache Pulsar is a messaging system like Kafka. It has topics, but as opposed to Kafka: It supports huge amount of topics, which results of 10k to 100k topics per broker.

Topic group are the key to reduce cardinality to still be able to monitor Pulsar.

You will have instruments for topic level granularity, each having 100k attribute sets (1 per topic), and instruments for topic group level granularity (1 per group), each having 1k attribute sets.

By default, topic level will be filtered out. You will group level instruments. Once you see a group misbehave, you turn it on to allow exporting only that group topics. This will be controlled dynamically by the user in the predicate that will be provided to the metric reader.

Once you understood and solved the issue, you can turn off the metrics for that topic group, and you can even decide to monitor a specific topic.

**Comment by pirgeo** [comment]
I see. What is the difference when compared to Views?

**Comment by jack-berg** [comment]
I think this could make sense. Couple of thoughts:

1. Would be good to see a performance comparison between reading all the data and applying the predicate in the reader, and pushing the predicate down into the SDK. It may be the case that even with a large number series, it doesn't make a impactful difference. For example, with the java SDK [prototype to reuse objects](https://github.com/open-telemetry/opentelemetry-java/pull/5178) allocations for reading metrics are brought to nearly zero. There could be some extra CPU overhead for reading all the metrics when only some are needed, but there's also additional CPU overhead for evaluating the predicate on every series. A benchmark would clear things up.
2. I think for completeness the predicate would need to accept all the parameters that describe each point, including scope, instrument name, type, description, unit, point kind, and attributes. The instrument name and description should be the names after any views have been applied, rather than before.

**Comment by asafm** [comment]
> I see. What is the difference when compared to Views?

1. Views are not dynamic. They are dictated on initialization.
2. Views are in scope of an instrument, not a single attribute set. You can either drop the entire instrument or not.

**Comment by pirgeo** [comment]
> Views are not dynamic. They are dictated on initialization.

Got it! Nicer to use, and probably a whole lot harder to implement 😄 

> Views are in scope of an instrument, not a single attribute set. You can either drop the entire instrument or not.

Two more questions: 
* Would you use the same instrument for two different cases (e.g. for reporting metrics on one topic and reporting metrics on one topic group)? If this is the case, it feels like comparing apples to oranges to me - but I might be lacking the context here. If this is not the case, I don't see the problem - then you do want to drop the whole instrument, right?
* If you don't drop the whole instrument, but only allow a few metrics streams for a certain instrument, then you cannot rely on the aggregate of these metrics anymore. E.g. if you record a counter in 5 places with different attributes, and then only export 3 of the metric streams, you cannot say "the overall sum is the sum of these three exported metrics" since you would be missing the two that were not exported. But, I guess that is what you are actually after since you don't always want all data, is that right?

**Comment by arminru** [comment]
@asafm Would you like to discuss this topic on the spec call tomorrow to move this proposal forward?

**Comment by asafm** [comment]
@arminru  I would, but unfortunately I can't today. I had a lengthy conversation with @jack-berg and @jmacd - I think they managed to understand the use case. If either of them will be present, they may be able to present the idea. If not, once the holiday season ends here, I will join the next meeting for sure.

**Comment by asafm** [comment]
@arminru I will try to join this Tuesday

**Comment by jmacd** [comment]
@asafm I understand that you are working out a way to offer debug-level metrics and have arrived at an approach where the reader supports a configurable predicate allowing you to skip through the data.

This led me to think through other possible ways to accomplish this, and I like your approach. As long as we're imagining, though, I think it's worth comparing alternatives.

One alternative is to let the SDK output high-cardinality data, send it to a collector, where (somehow) the level of aggregation could be dynamically controlled. Although we can find ways to describe varying-dimension data in OTLP, we are likely to run into problems at most consumers.

A similar alternative could output high-cardinality data to an intermediate representation, then re-process that data to reduce it to the intended level of detail at runtime. This might be more efficient than the collector-based re-aggregation, it is still more expensive than what you're considering.

One alternative might be to try to register dynamic views, but especially for UpDownCounter instruments (like counting items in a queue), the finest intended granularity (i.e., most dimensions) has to be aggregated from the start.

Your solution to the problems associated with varying-dimensions is to establish what I may call "dormant views", which are view configurations that are generally being calculated but not exported most of the time. When a user is diagnosing a specific problem, they could enable a specific dormant view and/or enter a predicate to report specific sets of attributes to a sporadically-reported timeseries used for debugging. You can turn the debug-level data on and off, without disturbing the ordinary group-level timeseries.

All the side effects associated with the SDK's Collect() would still take place when a predicate skips the output. All the callbacks are evaluated. If the reader is configured with Delta temporality, there will be gaps with missing data, if cumulative there will be gaps with average data.

I support this as an experimental option for SDKs to implement. I am wary of using "Filter" to describe this action of skipping data, I've used "skip" and "predicate" to avoid that word because that word is associated with reducing dimensionality in a View, and this is a separate mechanism.

**Comment by asafm** [comment]
What is the next step for this proposal? Write a PR?

**Comment by asafm** [comment]
@arminru @jmacd : What is the next step for this proposal? Write a PR?
