### ISSUE TITLE
Disallow `allow_custom_values: false` in semantic conventions

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-specification#3359]
Today, this field is used to generate language enums.  However, given the definition of stability for semantic conventions, this may limit some language from allowing new values in the future.  For now, we're removing this option to avoid falling into the trap of expecting values to be unchanging.

See [this dicussion](https://github.com/open-telemetry/opentelemetry-specification/pull/3225/files#r1150119273) for details.

**Comment by arminru** [comment]
Should we just disallow `false`, or remove the option entirely and make enums open by definitions?

**Comment by lmolkova** [comment]
> Should we just disallow `false`, or remove the option entirely and make enums open by definition?

I think both: on the spec level we should allow enums to be expandable. On the tooling/code-generation level we should use types that support expansion (usually not enums) so that the instrumentation library using schemaURL vX and enum value defined there can work with otel SDK/agent vX-1 and not explode. 
In azure-sdks,. we have implementations like this in each language (e.g. [ExpandableStringEnum in Java](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/util/ExpandableStringEnum.java) backed by map)

**Comment by Oberon00** [comment]
Currently allow_custom_values defaults to `false` in the tooling, so we will should definitely do tooling change https://github.com/open-telemetry/build-tools/blob/2e9bfeebd327d14a5c5c3daece9b48f756b78cb7/semantic-conventions/src/opentelemetry/semconv/model/semantic_attribute.py#L444-L447

**Comment by lmolkova** [comment]
Closing, this is addressed in semantic-conventions - we ignore `allow_custom_values` and will eventually remove support for it in the schema
