### ISSUE TITLE
[api-metrics] Mention of 'context' w/o definition.

### ISSUE THREAD

**Issue by freeformzSFDC** [open-telemetry/opentelemetry-specification#352]
Under Gauge, there is the following sentence: "The only difference between Observer and ordinary gauges is that their events do not have an associated OpenTelemetry context". https://github.com/open-telemetry/opentelemetry-specification/blob/27b738b74eeb10560dc0308554a1d626cb93df79/specification/api-metrics.md

What is an "OpenTelemetry context"?

**Comment by jmacd** [comment]
The terminology for distributed context has been shifting in the spec. In this context it refers to the correlation context and trace context.  Observer metrics were supposed to have been removed from the spec entirely in order to tighten up their definition, but this statement will hold true.  Observer metrics are set from a context-free callback and therefore cannot be associated with correlation or trace context.   Please refer to https://github.com/open-telemetry/oteps/blob/master/text/0008-metric-observer.md

**Comment by freeformzSFDC** [comment]
So does that mean the observer should be removed from the spec until the otep migrates from "proposed" to "accepted"?

**Comment by jmacd** [comment]
I think we should mark the OTEP as accepted. @bogdandrutu and I realized the specification wasn't complete, related to specifics about calling conventions for Observer metrics. It's fine to remove from the spec (it was an oversight), but it will come back. 

I (perhaps stubbornly) am refusing to write any new metrics-related OTEPs until the three outstanding PRs are resolved:
https://github.com/open-telemetry/oteps/pull/49
https://github.com/open-telemetry/oteps/pull/61
https://github.com/open-telemetry/oteps/pull/62

**Comment by jmacd** [comment]
This was addressed in the updates of #430.
