### ISSUE TITLE
How should a gauge overflow data point be aggregated?

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-specification#3614]
Currently the specification defines an over-flow attribute to be associated with ["a synthetic aggregation of the metric events that could not be independently aggregated because of the [cardinality] limit."](https://github.com/open-telemetry/opentelemetry-specification/blob/dc78006c12d9767fd2e35b691706c7572a76fd43/specification/metrics/sdk.md#overflow-attribute) How should this aggregation behave for gauges? Should it just hold the last-value of all attributes that fall into it? Should it sum the values?

The [original intent](https://github.com/open-telemetry/opentelemetry-specification/pull/2960) of the over-flow data point was to communicate a limit had been reached but still provide a way for totals (and rates) to still be calculated. If that is the case it would seen the gauge aggregation should sum all values for this attribute, right?

**Comment by jack-berg** [comment]
> Should it just hold the last-value of all attributes that fall into it?

^^ This. It would be odd to change the aggregation semantics just because an overflow took place. We assert that you should use an up down counter if its semantically meaningful to sum across the dimensions. If a user were to complain that they think the last value aggregation overflow behavior should be to sum, we should instruct them to use an up down counter instead.

**Comment by jmacd** [comment]
I suspect there will be a future where we can aggregate Gauge overflow into GaugeHistogram.
