### ISSUE TITLE
Document Java API: SpanBuilder API

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#37]
[Java repo](https://github.com/open-telemetry/opentelemetry-java) was used to combine APIs from OpenTracing and OpenCensus. 
Most of APIs are ready to be documented in a form of cross-language specification. 

SpanBuilder and the ways to construct Span needs to be described

**Comment by SergeyKanzhelev** [comment]
as discussed offline - assigning to you

**Comment by SergeyKanzhelev** [comment]
@songy23 while @c24t is on vacation - can you take this one?

**Comment by songy23** [comment]
Sure

**Comment by bogdandrutu** [comment]
In languages where builder patterns are not common like go, probably we should allow an implementation like a startSpan function where we allow a StartSpanOptions struct with all the capabilities that we have on the builder. Is that reasonable?

**Comment by tigrannajaryan** [comment]
>In languages where builder patterns are not common like go, probably we should allow an implementation like a startSpan function where we allow a StartSpanOptions struct with all the capabilities that we have on the builder. Is that reasonable?

This may not always be suitable. For example you do not always know all attributes that you want to include in the Span when the span is started. Sometimes the attributes become known after an operation that we want to observe has progressed for a while. And you cannot delay calling startSpan() function until this information becomes known because it would make the start time wrong. So this means that starting a span and setting its attributes cannot be done in the same builder call.

One possibility is to use the builder pattern in all languages. The benefit is that the OpenTelemetry API will be more uniform across languages. This is very useful for developers who work across multiple languages so they will not need to re-learn a new API when they want to use OpenTelemetry in a different language.

Alternatively, we could allow direct modification of Span via setters, not sure how feasible is that.

**Comment by SergeyKanzhelev** [comment]
> you do not always know all attributes that you want to include in the Span when the span is started

Span already support setters. Not everything can be set after creation. Like `SpanKind` can only be set on start. But attributes have setters.

I think in general SpanBuilder differenciate nicely between creation-only properties and other. So implementation can rely on those properties being immutable.

**Comment by tigrannajaryan** [comment]
Sounds good. So the proposal is to have `startStart(StartSpanOptions)` instead of SpanBuilder and allow the rest of span data to be modified via setters.

I wonder if it is still worth keeping the Builder pattern universally in all languages for uniformity. I do not have a strong opinion on this, there are cons and pros with doing it.

**Comment by carlosalberto** [comment]
> I wonder if it is still worth keeping the Builder pattern universally in all languages for uniformity. I do not have a strong opinion on this, there are cons and pros with doing it.

I personally think it would be better to suggest in the specification using builders, but not enforce them. For example, in Python it's not a good fit at all. I agree uniformity is good, but not at the expense of each language's conventions ;)

> a startSpan function where we allow a StartSpanOptions struct

Wondering if we could also allow parameters to appear directly, instead of a `StartSpanOptions` struct - this could be specially useful for languages with parameters with default values, such as Python ;) ;)

**Comment by SergeyKanzhelev** [comment]
@songy23 do you think you can send PR for this today?

**Comment by songy23** [comment]
Sure, sending a PR soon.

> I think in general SpanBuilder differenciate nicely between creation-only properties and other. So implementation can rely on those properties being immutable.

+1 to this. Builder is just a suggested form rather than an obligation of each language implementation. I'll send a PR based on the current Java Builder pattern but please feel free to suggest otherwise.
