### ISSUE TITLE
Define compatibility between cloud events and OpenTelemetry events

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-specification#3768]
[CloudEvents](https://cloudevents.io/) is a popular standard for describing event data. OpenTelemetry defines an [Event API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md) and has  an active [Event working group](https://github.com/open-telemetry/community/blob/main/projects/event-api.md) to resolve some of the outstanding issues related to the Event API / SDK and Events in semantic conventions.

Similar to the [compatibility](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/compatibility) documents we provide for Prometheus / OpenMetrics, OpenCensus, and OpenTracing, we should provide a compatibility document describing how CloudEvents interoperate with OpenTelemetry Events. 

We should be careful to ensure that any work done with the Event API / SDK and Events in the semantic conventions does not prevent interoperability with CloudEvents.

Additional context:

- https://github.com/open-telemetry/opentelemetry-specification/issues/2999: We considered using CloudEvents API instead of introducing an OpenTelemetry Events API. The idea was ultimately rejected.
- https://github.com/open-telemetry/opentelemetry-specification/issues/319: A long standing request for CloudEvent interoperation with OpenTelemetry. I believe we need a separate issue than this because I'm proposing specifics of how that interoperation works: A compatibility document which describes a mapping between CloudlEvents and OpenTelemetry Events.
- https://github.com/open-telemetry/opentelemetry-specification/issues/1949: Introduced semantic conventions describing [how to model CloudEvent messages](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/cloudevents/cloudevents-spans.md) as spans.

**Comment by pyohannes** [comment]
There are already [semantic conventions for tracing the flow of CloudEvents](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/cloudevents/cloudevents-spans.md), which are build on a [Distributed Tracing extension](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/extensions/distributed-tracing.md) that is part of CloudEvents.

It might be necessary to consider (and maybe re-work) this when defining a consistent relationship between OpenTelemetry events and CloudEvents.

**Comment by tedsuo** [comment]
I suggest that this issue be moved to semantic conventions. There are no compatibility issues.

The difficult design work involved collaborating with CloudEvents to design tracing for messaging systems. Structurally, CloudEvents are flat. All CloudEvents metadata can be mapped directly to attributes using the `cloudevent` namespace. CloudEvent data maps directly to the payload.  There are a handful of CloudEvent attributes which have not yet been added to semantic conventions, but I do not see any additional design work as necessary at this time. CloudEvents which do not have a tracing context must be stored as events, but otherwise they are no different than CloudEvents stored as spans.

For clarity, OpenTelemetry is intended to be a receiver of CloudEvents, not a producer which converts non-CloudEvents into CloudEvents. The same is true for tracing.

**Comment by tedsuo** [comment]
One other subject that should be addressed is integration at the instrumentation level. CloudEvents provides SDKs in many languages, which how they expect CloudEvents to be used. Unless we are planning on merging the projects and retiring the CloudEvents SDKs, I suggest that features should be added to the CloudEvents SDKs to allow them to send events to OpenTelemetry. 

This could be accomplished by emitting OTLP as a supported protocol, or it could be accomplished by calling the Otel API under the hood. It should be their choice as to how they want to add this support. 

I don't believe that we should add CloudEvent functionality to the Otel API, or otherwise encourage CloudEvent users to abandon the CloudEvent SDKs in favor of the Otel SDKs. I believe that there is more to CloudEvents that a simple API call, and they are much better equipped to keep up with the needs of their project than we are.

**Comment by pyohannes** [comment]
> For these reasons, I don't believe that we should add any CloudEvent functionality to the Otel API, or otherwise encourage CloudEvent users to abandon the CloudEvent SDKs in favor of the Otel SDKs.

:100: The scope of CloudEvents is much larger than that of OTel events. While the latter are restricted to telemetry, CloudEvents aims at supporting any workflows that involve events, see [here](https://github.com/cloudevents/spec/tree/main):

> CloudEvents is a specification for describing event data in common formats to provide interoperability across services, platforms and systems.

I assume we don't want OTel Event APIs to emit events that are used to control some business logic.

**Comment by tigrannajaryan** [comment]
@tedsuo @MSNev do you want to keep this open? If so let me know who is going to the assignee.

**Comment by MSNev** [comment]
We just decided that from the "event WG" perspective that this was not in scope (which is why we removed it from our board).

As the definition of a specific "event" would be for the event domain "owners" to specify in this case that would be someone who wants to create a bridge from Cloud Events to OTel. So we don't have anyone specific to be the assignee.

**Comment by tigrannajaryan** [comment]
Can we close this issue?
