### ISSUE TITLE
Define correct header to use for Correlation Context propagation

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-specification#461]
Adding this issue to track the recommendation from w3c discussed in https://github.com/w3c/correlation-context/issues/16 on what the correct header name to use it.

Discussion originated here: https://github.com/open-telemetry/opentelemetry-specification/pull/420#discussion_r378927350

**Comment by dyladan** [comment]
Giving this a bump since now the Correlations API is in the spec and the wording in the current spec doc states that we are using the w3c editor's draft. I just want to state that I believe this is a dangerous idea as the spec is currently under heavy maintenance and things like the header name and/or the format of the value itself are likely to change. I think at the very least we should vendor-prefix our header name so we don't send/expect invalid headers when the spec is changed and finalized. A vendor prefixed name would also make an upgrade path very straightforward using the composite propagator.

**Comment by bogdandrutu** [comment]
We went to use a different name and format for the moment.
