### ISSUE TITLE
Questions WRT naming inconsistency between spec and SIG

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-specification#480]
We have two open issues in JS https://github.com/open-telemetry/opentelemetry-js/issues/795 and https://github.com/open-telemetry/opentelemetry-js/issues/794 which deal with renaming things we already had names for in order to make them use the same names as the spec. In general, is this required/encouraged by spec or should we just keep the names we already have?

**Comment by arminru** [comment]
I think it makes sense to have the names aligned across languages and with the spec since this makes it easier for people who use multiple languages or want to read up on the concepts in the spec.

We are currently fixing deviations in otel-java, for example: https://github.com/open-telemetry/opentelemetry-specification/issues/476

**Comment by thisthat** [comment]
Java issue for the consistency check: https://github.com/open-telemetry/opentelemetry-java/issues/794

**Comment by reyang** [comment]
I think we should align with the spec as much as possible. The only exception is when the name wouldn't make sense for a particular language (e.g. conflict with a reserved keyword, would introduce big confusion as the name already established a different meaning).
