### ISSUE TITLE
Metrics: SDK should raise an exception on duplicate names for different instrument types?

### ISSUE THREAD

**Issue by toumorokoshi** [open-telemetry/opentelemetry-specification#498]
Just wanted to throw an issue out for discussion, while the metric SDK is being designed.

Should we reject an instrument with the same name being created against the same Meter, or MeterProvider?

We ran into an issue internally where someone used the same key for two different instruments, causing the final value to be incorrect.

I could imagine that there's some argument for having the same kind of instrument with the same name, but I wonder if it's a better safeguard to reject two different kind of instruments with the same name. (e.g. observer and counter).

**Comment by Oberon00** [comment]
Regarding the question from the title: I'm pretty sure we don't want to throw exceptions, as that would violate the error handling guidelines: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/error-handling.md#basic-error-handling-principles

**Comment by jmacd** [comment]
The current specification states "The Meter will return an error when a metric name is
already registered with a different kind for the same name."

This behavior is not implemented in the Go implementation -- I'll fill issues. In the Go idiom, I plan to propose we add an optional `Must`-prefixed version of each constructor that will panic instead of returning an error. This allows metric instruments to be declared for the global SDK in static `var` blocks.

**Comment by toumorokoshi** [comment]
@jmacd great! should I just close this issue then?

**Comment by toumorokoshi** [comment]
rather, I'll close this comment, and reopen if it's still needed for some other clarification.
