### ISSUE TITLE
Should spans provide a way to get events?

### ISSUE THREAD

**Issue by toumorokoshi** [open-telemetry/opentelemetry-specification#532]
The opentelemetry api specification currently specifies a way to ADD events, but no way to retrieve them. There's also a mention of the schema of such an event, but it's slightly ambiguous that we actually need some sort of event struct to help represent such an object.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#add-events

I'm clarifying whether this is intended, or should be added. With the current specification, it's actually possible to not provide an Event object at all and satisfy the specification, as it just calls for an interface to pass in parameters that would construct such an object:

Bringing this up as there is currently a PR in python to move events to the SDK. which I feel like isn't what's intended but still satisfies the current specification:

https://github.com/open-telemetry/opentelemetry-python/pull/474/files

**Comment by pauldraper** [comment]
Generally speaking, nothing in tracing or metrics API is "retrievable." This allows performant no-op implementations and conforms the idea that observability should not affect function.

In a scripting language like Python (with no "interfaces"), there's actually *very* little that should be in the API. Just no-ops, global setters and enums/constants.

**Comment by Oberon00** [comment]
>  I feel like isn't what's intended

Do you see any drawbacks to not having this in the API? I can see two advantages of not having it in the API:
* Smaller API surface: Easier to learn, gives more flexibility to implementations
* No question of reference vs value semantics ("will updating the event object after I add it to the span be reflected when the span is exported"?)

So I'd say, since there is no explicitly specified interface object for the set of attributes that are supplied at span start, there is no need for an explicit event object either. Some EventBuilder class might be advisable to have tough, depending on language conventions and features like named function arguments.

**Comment by toumorokoshi** [comment]
> Generally speaking, nothing in tracing or metrics API is "retrievable." This allows performant no-op implementations and conforms to the idea that observability should not affect function.

I think that's fair. I understand the intent is to more allow creation of such things, rather than expose data.

> Do you see any drawbacks to not having this in the API?

One drawback I see is there's no APIs to modify events after they've been added. I could imagine someone on the application side wanting to add or modify their event after the fact. But this could also be argued to be a rare edge case, as deferred adding of the event is an acceptable alternative. 

I think I'll close this issue and there's good counterarguments raised here. thanks for clarifying :)
