### ISSUE TITLE
API: Describe Status class

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#59]
Describe `Status` class and canonical codes

**Comment by rochdev** [comment]
As described in https://github.com/open-telemetry/opentelemetry-node/pull/31#discussion_r293864070, I'm not a fan of this concept in general. It's basically impossible to have a range of values to cover every use case. There is also not enough information included to actually understand the source of the error if any.

I think it would be more flexible to have an error code as an arbitrary string, a message, and a stack trace if it applies. This would provide a lot more flexibility and details about the source of any error.

**Comment by SergeyKanzhelev** [comment]
@rochdev can you please create a separate issue for this and we will mark it with the next milestone for the discussion

**Comment by draffensperger** [comment]
IMO one of the goals here is to try to standardize the different status codes for RPC transports (gRPC, HTTP, Thrift, etc.) so that trace analysis and visualization tools could have a standardized least-common-denominator concept of status to know that e.g. something is a user error vs. a server timeout vs. a permissions error even if it doesn't know the fine-grained original status reason.

Would it work for the different HTTP transports to have standardized span labels for their specific status codes? OpenCensus used that approach, see [Mapping from HTTP status codes to Trace status codes](https://github.com/open-telemetry/opentelemetry-specification/blob/4ac49aa1e86633887f49ab1f58221b78b4888e24/work_in_progress/opencensus/HTTP.md#mapping-from-http-status-codes-to-trace-status-codes) and [HTTP Span Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/4ac49aa1e86633887f49ab1f58221b78b4888e24/work_in_progress/opencensus/HTTP.md#attributes). (Note those are OpenTelemetry spec links but seem copied from OpenCensus and are marked WIP.)

And for the stack trace, could we just have a stack trace property of a `Span`, which then allows associating stack traces even to successful spans? I think `Status` does have a full description field so that at least is included there I believe.

**Comment by SergeyKanzhelev** [comment]
@draffensperger I'm sorry I lost the sense of what you are proposing to change. In any case, this issue is to describe what was proposed in Java specs so we will have a baseline to start discussions from.

@tedsuo do you think you gonna finish with it soon?

**Comment by rochdev** [comment]
@SergeyKanzhelev From the description of @draffensperger I think this may be useful in a few contexts. However, the most important error code (500 Internal Server Error) doesn't seem to be included. Which code should be used for exceptions?

**Comment by tedsuo** [comment]
Throwing in the towel on this one! Apologies, I'm unavailable for the next two weeks.

**Comment by carlosalberto** [comment]
I can take this one.

**Comment by SergeyKanzhelev** [comment]
@rochdev good point that is was missing from the mapping table. Must be "Unknown" as it is an unknown error on server side.

**Comment by draffensperger** [comment]
I noticed there is also an [INTERNAL](https://github.com/open-telemetry/opentelemetry-js/blob/802182ee095896cd36c7f29bbf48d0ef169b2047/packages/opentelemetry-types/src/trace/status.ts#L146) status code. Could that be the right status for an internal server error?

**Comment by SergeyKanzhelev** [comment]
@draffensperger 500 is about the error you simply don't know details for. You still made a successful communication. Internal is when library crashed attempting to establish communication or parse the response. In http world it will most probably be one of client library exceptions, not a status code based one.
