### ISSUE TITLE
Semantic conventions for request / response size

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#640]
I think it's common for spans to contain attributes for the size of a request or response. Would it make sense to add these conventions for HTTP which mark the number of bytes in a request or response body (0 if there is no body, headers wouldn't be included)?

**Comment by arminru** [comment]
Sure, feel free to make a PR adding these to the spec.
Personally I think it's better to have more (optional) attributes defined than too few, because the consequence of missing attributes will be that users/instrumenters have to come up with their own, which makes it harder for backends to analyze them. It's better to align key names and semantics right from the start before there are dozens of different names used in different instrumentations, with same or slightly different semantics.

I wouldn't make them required, however. In some cases, HTTP requests are just passing through services without having their content decoded and processed, so the body size might be dispensable for them (even though just getting the size should be trivial).
We also have optional attributes defined for message sizes, so you could have a look at these to stay consistent:
https://github.com/open-telemetry/opentelemetry-specification/blob/1729bc4337bdc1df83ff7eab53eb7405d6e75665/specification/trace/semantic_conventions/messaging.md#L65-L66
