### ISSUE TITLE
Markdownlint extremely flaky

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-specification#668]
I think I've had about a 10% success rate with markdown-link-check since it seems to get throttled by GitHub. I've heard this was an issue that should have improved, but it doesn't seem to have been and I can't find any context for that in this repo.

Perhaps switching markdown-link-check to a GitHub Action would work around the throttling "for free" (actions automatically have GitHub creds for the repo). Just an idea.

**Comment by Oberon00** [comment]
Or we have to exclude github.com from link check for the moment. It has really become annoying.

**Comment by arminru** [comment]
Recently the success rate has decreased to close to zero which is really annoying and renders the whole checker useless since the failing builds will always just be ignored.

It seems like using a Github action wouldn't solve the issue either according to these comments:

https://github.com/tcort/markdown-link-check/issues/94#issuecomment-634947466
> In my case, I would like to filter out `HTTP 429 Too Many Requests`. This happens when I'm checking links to github.com repositories using github workflows

https://github.com/tcort/markdown-link-check/issues/94#issuecomment-640250602
> We have the same exact use case and issue as @ koppor with a GitHub Actions workflow checking links against github.com, where it can occasionally return a 429 status code for random links. In our case we would be okay to ignore those although ideally it would retry.

It would probably be best to just exclude github.com from the check for now and just hope that no restructuring/moves/edits in open-telemetry/oteps, open-telemetry/opentelemetry-proto or other referenced repos go unnoticed.

**Comment by arminru** [comment]
If we go with the Github action, I think it should be possible to build a solution that gets a Github API Token from the [action's secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token), populates a placeholder in the [markdown-link-check config file](https://github.com/tcort/markdown-link-check#config-file-format), which in turn adds the token to the authentication headers for each request hitting github.com.

**Comment by bogdandrutu** [comment]
Recently things got better.

**Comment by tigrannajaryan** [comment]
This is indeed annoying but I don't think it blocks the GA. I suggest to remove `release:required-for-ga` label.

**Comment by andrewhsu** [comment]
From the issue triage mtg today, i'm changing the label to `release:after-ga` since it looks like from the comments this can be punted.

**Comment by Oberon00** [comment]
Is this still actionable?

**Comment by chalin** [comment]
Drive-by comment: I think that this is mis-titled. The title should read **markdown-link-check extremely flaky**, right?
