### ISSUE TITLE
API: remove Span.recordSpanData from the API specification

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-specification#71]
In the Java prototype, `SpanData` has been exposed as an alternative way for an application to submit spans. This was justified as a means of forwarding spans constructed out-of-band, e.g., for transforming logs data into span records.  I can't find the original discussion that led to this, but would like to formally propose removing `SpanData` from the user-facing instrumentation API because it is not meant for instrumenting.

In my view, `SpanData` is part of the default exporter--a part of the OpenTelemetry SDK specification, but not a part of the instrumentation API.  There will be other implementations built for this API that target different exporter models, and requiring those exporters to accept `SpanData` inputs is a burden.

Specifically, in the Java prototype we have removed the ability to explicitly set a start time or an end time. This creates two hurdles, one for the implementor and one for the instrumentor.

1. An implementation of the API that does not directly export `SpanData` is forced to accommodate a new, otherwise unnecessary data type, which increases the size and footprint of the code.  Say an implementation is designed to record low-level events to an external processor.  To implement `Span.recordSpanData` requires emulating the events that would be recorded for that span, so they're going to have to accommodate spans with user-provided timestamps, but they have to implement two code paths since `recordSpanData` cannot be implemented in terms of other `Span` APIs.

2. An instrumentor is faced with a burden too. Suppose (using Go, for example) you're implementing gRPC middleware and want to use the `golang.org/grpc/stats.Begin` and `golang.org/grpc/stats.End` events to start and finish spans. You've been given correct start and end timestamps, but in order to use those you would have to construct a `SpanData` object, instead of calling `Span` APIs as you otherwise would.

The suggestion here is that it should be possible to implement `recordSpanData` in terms of the `Span` API. This means supporting new span options to set the start and end time.  Then, `recordSpanData` can be implemented as a helper, which simply turns `SpanData` into a sequence of `Span.Builder` calls.

If there is a concern that it is difficult or awkward to translate out-of-band spans into `Span` API calls, we should focus on those problems specifically. In OpenTracing, the problem was that Resources were not a first-class part of the API, so it was confusing to think about forwarding spans through the `Span` API. With explicit Resources part of the API, we should be able to record out-of-band spans using the `Span` API.

**Comment by bogdandrutu** [comment]
I am concerned that we will need to have Timestamp on a lot more methods/functions in order to allow this via Span. That will probably make the API larger.

**Comment by jmacd** [comment]
In OpenTracing, it required just two new options, one on Start and one on Finish. I can't see how it would require more than two new optional parameters.

**Comment by bogdandrutu** [comment]
What about Events? Do we not want to have the ability to set a Timestamp for them?

**Comment by jmacd** [comment]
This is important for the case where the API's Span.Event() method is called from within a logging library integration. See the OpenTracing Java call: https://github.com/opentracing/opentracing-java/blob/d91d7072e141fa66265946b5164c249bf3045017/opentracing-api/src/main/java/io/opentracing/Span.java#L87

If it were an SLF4J integration, you'd want to use the `getTimeStamp()` value of the  `LoggingEvent` (https://www.slf4j.org/apidocs/org/slf4j/event/LoggingEvent.html).

**Comment by discostu105** [comment]
I support the proposal to remove recordSpanData from the API.

For us, the problem is: We implement a Tracer, which strictly relies on creating our own datastructures (with additional information) on-thread (sync) for various reasons. Having to implement an API like this would mean, we'd have to reside with the information given, using a correlation mechanism (via trace-id/parent-span-id) that we did not chose for ourself.

IMHO "recordSpanData" is an exporter-feature and it should go into a different API/package.

**Comment by SergeyKanzhelev** [comment]
@discostu105 how would you propose to address the need to report spans asynchronously? Take a direct dependency on SDK?

**Comment by jmacd** [comment]
With a `recordSpanData` API, the instrumentation API includes both a procedural way to report traces and a data-oriented way to report traces. I still feel that one mechanism should be sufficient, and that if the procedural mechanism for starting traces (i.e., the builder pattern, or whatever constructor pattern is idiomatic) is *complete*, then the data-oriented mechanism can be implemented on top of the procedural mechanism.

As we've discussed, this requires the procedural mechanism to support setting the timestamp, as well as (probably) a way to indicate that the span data was not collected locally. I view this as the right approach for scenarios where the trace has to be started before the name is known, or similarly, for setting the timestamp if a tracing handler is called after the true start of the operation.

I feel these special cases that require setting a timestamp are still important for the procedural mechanism, since we need real Span API objects that can be set in the active scope.

**Comment by bogdandrutu** [comment]
I spent a lot of time thinking about this, and want to document some of my thoughts (I talked with @SergeyKanzhelev and @jmacd about this as well). These represents my thoughts not their, I mentioned them here for context, but they may have different opinions than mine.

## Use Cases
1. Span is recorded synchronous but for some of the events (like start/end/an event) a sync hook is not provided or even impossible provide. An example here can be an RPC system that records the time when the first byte for a message is received (but not all data are received and parsed) then after headers are parsed a Span can be created and a better start time is available (recorded when the first byte was received).
2. Span is recorded completely asynchronous. An example can be a library that offers a "sink" pattern where async events are delivered containing all the information about every request, another example can be constructing Spans from logs. In this case creating a Span object is unnecessary and any extra information recorded about the process is not correct (e.g. cannot record stacktraces, cpu-usage, thread-id, etc.).
  * In order to support this use-case it is required to have a way to generate a SpanId (in the external source).

## SpanData
First use-case is partially supported; The problem is that it does not allow some events to be sync and some async:
* Pros:
  * Allows the implementation to rely on the fact that all events are recorded sync (can record for example the stacktrace associated with every event).
  * Allow implementation to enforce time ordering for all the events recorded via Span API and rely on the fact that all the spans recorded via SpanData are not necessary ordered.
* Cons:
  * API needs to expose a way to generate a child SpanContext in some way. Currently the 
  * No way to set an "current active" Span in the Context.

Second use-case is supported;

## Allow Timestamp on Span events (start/end/event)
I would assume that this pattern is combined with a property that user can set when they start a Span to mark if the Span is sync (events are guaranteed to be generated by this process but could be in a different thread or different stacktrace) vs async reported (no guarantee that the events are generated by this process).

First use-case is supported:
* Pros:
  * Relies on the same Tracer logic to create a SpanContext (hopefully the startSpan is called before any need to serialize this on the wire or to create a child Span).
  * Allows the Span to be set as "current active" Span in the Context.
* Cons:
  * Reported Spans can have events with different time sources (a lot of languages have different sources). Events recorded with an external timestamp cannot be ordered correctly (in general we want to use a monotonic time source for events inside a Span to ensure ordering but this is not possible).
  * If an implementation wants to record cpu-usage when start a Span, the version with a Timestamp is used then the cpu-usage is associated with the call to startSpan not when the "logic span operation" started. There may be other things to consider here like (thread id).

Second use-case is supported if the sync vs async report flag is supported.
* Most likely this requires a capability to start a Span with a given SpanID, and will not allow implementation to change the TraceState because everything already happened.

## Extra thoughts
1. Do not support the first use-case in the API.
    * This is not possible because it is a common pattern in RPCs or proxies like Envoy for example.
1. Do not support the second use-case in the API.
    * This is not acceptable especially if this happens in the same process where other Spans are generated sync.
    * It will require vendor specific dependencies for all these cases if not supported.
    * With the community power we may have a chance to avoid supporting this by putting pressure on all the libraries to support our needs.

## Personal conclusion
Overall (especially because of the fact that SpanData requires the API to expose the logic of creating child SpanContext (spanID, manipulate TraceState, etc)) I believe that for the first use-case allowing users to set timestamps for every timed event is significant better than SpanData, for the second use-case the SpanData is a bit cleaner but I can live without SpanData for this.

**Comment by bogdandrutu** [comment]
@discostu105 if you want to support the second use-case that I described in my previous comment you will need to support something very similar with the current SpanData where you cannot manipulate the SpanContext or anything synchronously.

**Comment by discostu105** [comment]
@bogdandrutu thanks for your thoughts and your detailed answer.

## Use Case 1 (sync API calls) 
I think this would be doable with providing timestamps at startSpan/endSpan. However, if there is an API that provides *timestamps*, we have to talk about timeproviders. Which source would provide that timestamp? Not only the resolution and epoch of a timestamp needs to be specified, but more importantly it's source. Time is subject of drift, can vary on different hosts on, can be re-set by NTP or user etc. 

To solve this, a *Tracer* could offer an API that provides a Timeprovider implementation, which is up to the tracer. Has such a discussion happened so far? Is this something you think is feasible?

## Use Case 2 (span data sink)
While I get the use-cases for this, it is a completely different approach to capturing spans. Some more examples, why this differs significantly to Use Case 1

 * In our datamodel (dynatrace), we put a "marker" in the parent-span when a child-span is to be expected. We know this at the time of context-propagation for example. This makes correlation of parent and child spans easier. Anyway, if spans arrive completely asynchronously, these "markers" are not present. We need to employ a different model of correlation. While doable, it imposes a difference that makes our life harder.
 * Extraction/Injection of special tracing headers (TraceState entries) is not possible, which also breaks some use-cases for us.
 * Recording of CPU-times or capturing stacktraces not possible.

So, in my opinion, the need to support both use-cases in a Tracer implementation just makes things harder for implementers, while it's probably doable for us. I'm wondering what other implementers think about this? @mwear?

Would it make sense to move this specific API to a different interface, or a completely different package? E.g. the SDK package. Or some specific "exporter-interface" package?

**Comment by bg451** [comment]
The idea of removing SpanData came up in https://github.com/open-telemetry/opentelemetry-js/pull/72, primarily around concerns of adding a new API to an already large API. It's awesome to see that there's movement towards removing it. I'm going to start an RFC. I'll link it here once I have a draft; also happy to collaborate on it with anyone else interested. 

Also if anyone has code example of out of band span creation, I'd love to see it to get a stronger idea of the use cases. For example, at LightStep, we have [these](https://github.com/lightstep/splunktospan/blob/master/splunktospan/span.py#L43) [two](https://github.com/lightstep/haproxy_log2span/blob/master/lib/lib.go#L292) libraries to translate logs to spans.

**Comment by SergeyKanzhelev** [comment]
This was completed
