### ISSUE TITLE
Remove exportTimeoutMillis for exports

### ISSUE THREAD

**Issue by huntc** [open-telemetry/opentelemetry-specification#718]
The specification mandates the declaration of an export timeout that should instead be relegated to exporters:

> exportTimeoutMillis - how long the export can run before it is cancelled. The default value is 30000.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#batching-processor

Depending on the language, the SDK has limited ability to cancel an export that is "in-flight". On the JVM, if exporting is performed asynchronously, then it will be on a thread out of reach to the SDK, and not able to be cancelled.

All configurations associated with the long-lived operations, including timeouts, should be relegated to an exporter. The exporter is also in the best position to determine this configuration given the type and nature of the network within scope (if any).

The `exportTimeoutMillis` should be removed.

cc @jkwatson

**Comment by Oberon00** [comment]
Another idea would be to add an `abort()` method to the exporter interface that the span processor could call.

**Comment by huntc** [comment]
> Another idea would be to add an `abort()` or `cancel()` method to the exporter interface that the span processor could call.

There is already a shutdown method on the exporter.

**Comment by Oberon00** [comment]
> What are the use cases for cancellation other than coping with a badly behaved exporter?

Helping an exporter cope with a badly behaved network connection?

**Comment by huntc** [comment]
> > What are the use cases for cancellation other than coping with a badly behaved exporter?
> 
> Helping an exporter cope with a badly behaved network connection?

I’m not sure how. An exporter is in the best position to deal with connectivity. Are you able to elaborate?

**Comment by Oberon00** [comment]
I think either way would work but currently I think for example Java starts the exporter in a separate thread so that it can interrupt that thread if it times out (and in any case, not delay the start of the next export). If the span processor can fully trust the exporter to handle the timeout that is also a valid design but I expect many exporters will end up with code similar to

```java
ResultCode export(...) {
  Thread t = new Thread(actualExportCallback);
  t.start();
  t.join(timeout);
  if (there was a timeout) {
   t.interrupt();
  }
}
```

So sharing this code between different exporters would make sense. Maybe exporter chaining would be better for that though, see https://github.com/open-telemetry/opentelemetry-specification/issues/716#issuecomment-660598719. That would give the exporter implementer the choice to reuse this timeout handling code or implement some custom logic, instead of being forced to have the timeout (also) enforced by the span processor.

**Comment by huntc** [comment]
@Oberon00 Thanks. Your code relies on the exporter to block as indeed is the current behaviour. My request is indeed also influenced by my desire to see the export api become async as per https://github.com/open-telemetry/opentelemetry-java/pull/1428.

**Comment by huntc** [comment]
I'm going to close out my issue here as I realised that there is use for timing out after all. While attempting to interrupt exporter threads is incorrect for Java (only the exporter knows what threads are in progress), more broadly, an exporter can be "asked" to cancel. Thanks for the dialogue and for tolerating my question here.
