### ISSUE TITLE
Add recommendations about blocking / queuing / resource consumption for language libraries

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-specification#94]
From: https://github.com/open-telemetry/opentelemetry-specification/pull/84#discussion_r292158584

>Some design principles we could explore:
>
>    The SDK/exporter should not block the customer's code (except for explicit call to flush and a grace exit), the SDK would rather drop data instead of eating up all the resources.
>    The SDK/exporter should have a confined resource consumption, e.g. max memory / max network bandwidth.

**Comment by saiya** [comment]
From a user point of view, I strongly agree with the principle `The SDK/exporter should not block the customer's code`. It is difficult to allow tracing SDK to block application in large / chaotic system (my company is operating such system).

In OpenCensus, I proposed pull request and discussed about the blocking issue (in https://github.com/census-instrumentation/opencensus-java/pull/1837, https://github.com/census-instrumentation/opencensus-specs/issues/262). OpenCensus developer suggested me to wait for OpenTelemetry instead of improving OpenCensus to implement non blocking tracing.

Are there anything I can help/contribute to state the principle explicitly in OpenTelemetry specification documents ( specification/library-guidelines.md)?

**Comment by songy23** [comment]
Like I mentioned before in https://github.com/census-instrumentation/opencensus-java/pull/1837#issuecomment-499748711, I personally prefer to provide the configuration on blocking/non-blocking through static configs, like manifest/environment variables/flags etc.

> Are there anything I can help/contribute to state the principle explicitly in OpenTelemetry specification documents ( specification/library-guidelines.md)?

Speaking of contributions, I think library-guidelines.md is good place to start with since non-blocking will affect the overall behavior of the library (unless others have a better suggestion here).

**Comment by jmacd** [comment]
@tigrannajaryan Would you say that this can be closed? I believe library-guidelines.md discusses this topic.

**Comment by jmacd** [comment]
If this is still needed, please reopen.
