### ISSUE TITLE
Should SpanData support lazy-calculated properties?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-specification#96]
Related to:
https://github.com/open-telemetry/opentelemetry-specification/issues/95

**Comment by SergeyKanzhelev** [comment]
Text may be:

`SpanData` MUST be an abstract class or interface. As `SpanData` is used for the
code instrumentation, it is NOT expected alternative implementations of a
`SpanData` will be supplied by consumer of telemetry (i.e. telemetry vendor).
Typical use case for alternative implementations is to implement lazy
calculation of properties and minimize the number of allocation required at
instrumentation point. So it will be done by instrumentation code. For instance,
alternative implementation of `SpanData` may hold a reference on an object. And
all getters will be implemented by lazily calculating the required properties at
a moment that `SpanData` is passed to one of exporters.

Implementations of `SpanData` MUST return the same value in getters when that
getter was called multiple times. It is also discouraged to throw exceptions
from getters. Default value or value indicating an error SHOULD be returned
instead if possible.

**Comment by jmacd** [comment]
[Not sure if this is stale or should be closed. I have related questions.]

I see a lot of value in having a way to support lazy values, but I feel it would be a shame if I was forced to use the SpanData abstraction for a _whole span_ when my existing code uses an active Span object already. 

OpenTracing didn't firmly specify support for a lazy value type, but it has been implemented in some of the opentracing Event (Log) APIs. E.g., https://github.com/opentracing/opentracing-go/blob/master/log/field.go#L149

We SHOULD have a way to log lazy values so that code can benefit from a live Span object without use of SpanData.

I'm sorry to continue raising the campaign against SpanData (issue 71), but it appears to be being used for an application that is not strictly OUT-OF-BAND reporting here. This "lazy calculation" application does not really apply if the span data was reported out of band, right?  This means SpanData can be a plain object / struct, not an abstract class or interface, contrary to what was written above.

**Comment by SergeyKanzhelev** [comment]
If #71 will be resolved by removing SpanData abstraction - many issues can become irrelevant. This one perhaps may be re-purposed to raise the question whether the entire `Span` can be lazily calculated. For instance, entire attributes collection.

**Comment by SergeyKanzhelev** [comment]
SpanData was removed. Closing the issue
